### ISSUE TITLE
toggle all breakpoint if i find all constant

### ISSUE THREAD

**Issue by cxj98** [x64dbg/x64dbg#467] opened 2015-12-20 06:39 UTC
can you make toggle all breakpoint if i find all constant like:

add esp, -0xc
mov dword ptr [edx + eax4 - 0xc], ecx
mov dword ptr [eax + ecx4 - 0xc], edx
mov dword ptr [ebp - 0xc], 4

current can toggle breakpoint use F2 one by one manually, any possible use mouse right click popup a menu toggle all? thanks.

**Comment by mrexodia** [comment] 2016-02-25 02:21
duplicate of #160

**Closed by mrexodia** 2016-02-25 02:21 UTC
Labels: feature
