### ISSUE TITLE
Memory search exception in x32dbg

### ISSUE THREAD

**Issue by dooley71** [x64dbg/x64dbg#880] opened 2016-07-23 15:32 UTC
Hi all,
I am having an issue that hopefully someone can help me with.

It seems that lately, every time I search memory for a pattern (in any assembly) I get a page guard exception and can no longer continue debugging. I can search the same exe memory with ollydbg and don't get an exception.

I was wondering if there is a setting in x32dbg that I am unaware of that is causing this? Is there a way to skip guarded memory during a search?

I don't remember this being an issue when I first started using x32dbg. 

Thanks In advance.

**Comment by mrexodia** [comment] 2016-07-23 15:32
duplicate of #877

**Closed by mrexodia** 2016-07-23 15:32 UTC
