### ISSUE TITLE
[New Feature] Names list for current module or all modules like "Names list" in Olly

### ISSUE THREAD

**Issue by ThunderCls** [x64dbg/x64dbg#336] opened 2015-07-12 20:47 UTC
x64dbg has a "Symbols" tab where you can check, search and place breakpoints on any import wanted from the modules being used by the process, nevertheless it's a little tricky to locate and manage API's functions used by the debugged proc. It would be really great to have the "Names Lists" feature that Olly have for listing and managing names in a better and easy way. It would be awesome to have this features shown in the pictures

![capture](https://cloud.githubusercontent.com/assets/13303069/8639916/55db3bc6-28a4-11e5-90af-ea5a45be718c.jpg)

![capture2](https://cloud.githubusercontent.com/assets/13303069/8639917/5aad373a-28a4-11e5-8d12-899b0b9823bf.png)

**Comment by mrexodia** [comment] 2015-07-13 01:56
luckily this was already implemented.

![intermodular calls](http://i.imgur.com/1KFmgyT.png)

**Comment by ThunderCls** [comment] 2015-07-13 02:56
@mrexodia You are right, it has "Intermodular calls" implemented, but still, let's say I've got an app that has, I don't know, maybe 30 calls to MessageBox API, then if I want to put a breakpoint on each one of those calls, I'll have to go through all of that never ending intermodular call list setting breakpoints on each and every one of those 30 MessageBox calls. Even let's say that I use the search feature to filter just those MessageBox functions, but still I have to click on all of them to set the bps, at least it's needed a menu option to set/unset those 30 bps with just one click, maybe "Set breakpoint on every command", "Remove breakpoint on every command" and "Toggle breakpoint on import" for a certain API. Again, this is just a small suggestion to make things with this dbg a little easier and faster.
Greetings

**Comment by mrexodia** [comment] 2015-07-13 03:00
so then it would be a duplicate of #160 ?

The obvious thing to do would be a breakpoint on MessageBox directly, but I see what you want. #160 should do the job.

**Comment by ThunderCls** [comment] 2015-07-13 03:40
Ok you can mark it as a duplicate of the issue #160 then, and if you have some time left to add the option to set de bp directly on the import of the API through the reference, to prevent the user of having to press enter twice, one over the reference, the other one on the code to go to the import and then finally press f2, why are you gonna do all that job, if you can have all of that done by a simple mouse click ;p xD

**Closed** 2015-07-13 04:59 UTC

**Comment by mrexodia** [comment] 2015-07-13 05:11
![img](http://i.imgur.com/vcP9Y7f.png)
