### ISSUE TITLE
Some error in pattern search

### ISSUE THREAD

**Issue by gmastergreatee** [x64dbg/x64dbg#1285] opened 2016-11-22 16:37 UTC
![asdasd](https://cloud.githubusercontent.com/assets/17880848/20532401/dc6bb014-b0ff-11e6-9a5d-06402b2f633f.gif)

**Comment by gmastergreatee** [comment] 2016-11-22 16:41
Please also add the feature to display unicode strings while searching for "String References"

**Comment by mrexodia** [comment] 2016-11-22 17:15
Please create separate issues for that and also check if there are none
open for that.

**Comment by gmastergreatee** [comment] 2016-11-22 17:17
Already checked before posting above comment, created #1286

**Comment by changeofpace** [comment] 2017-01-21 02:57
this should be fixed with 9213d8f1173dbc3b0afda9f6eb1c078276eb1194

**Comment by mrexodia** [comment] 2017-01-21 13:13
@gmastergreatee The issue is assumed to be fixed. Please try and confirm.

**Closed by mrexodia** 2017-01-21 13:13 UTC
Labels: bug

**Comment by gmastergreatee** [comment] 2017-01-23 13:50
Working perfectly, thanks.
