### ISSUE TITLE
evaluation of logical operations

### ISSUE THREAD

**Issue by zashraf1337** [x64dbg/x64dbg#1834] opened 2017-12-12 23:14 UTC
Hello,

```
0 && dword:[0x4]
```
results in 

```
Failed to read memory
Unknown command/expression: "0 && dword:[0x4]"
```

I would expect it to not evaluate `dword:[0x4]`

Use case: e.g. it can be used in conditional breakpoints.

**Comment by mrexodia** [comment] 2017-12-12 23:15
duplicate of https://github.com/x64dbg/x64dbg/issues/931

**Closed by mrexodia** 2017-12-12 23:15 UTC

**Comment by yiivon** [comment] 2021-09-29 17:22
I wanna implement this logical issue, think about that how x64dbg could filtering LVN_GETDISPINFO out of WM_NOTIFY like as `arg.get(1) == 0x4e && ([arg.get(3)+8]==0xFFFFFF6A || [arg.get(3)+8]==0xFFFFFF4F)`
