### ISSUE TITLE
Cannot modify the MxCsr register

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#1102] opened 2016-09-19 16:06 UTC

**Comment by mrexodia** [comment] 2016-09-20 00:18
I reproduced this, not sure where the issue is coming from.

**Comment by torusrxxx** [comment] 2016-09-25 14:40
The MxCsr register cannot be modified even on a very old release.

**Comment by mrexodia** [comment] 2016-09-25 16:32
It should be fixed in titanengine now.

**Closed by mrexodia** 2016-09-25 16:32 UTC
Labels: bug
