### ISSUE TITLE
Multi-threaded breakpoint program crashes

### ISSUE THREAD

**Issue by fyc132** [x64dbg/x64dbg#2168] opened 2019-05-09 04:28 UTC
Write a simple program:
![QR4E V4T7M86DGLWSJRCMCQ](https://user-images.githubusercontent.com/16433238/57426980-74912780-7254-11e9-967d-165a80a2d79a.png)

Set breakpoints for thread1 and thread2
![V25XG03H 48HQ{3Q%R~0HCF](https://user-images.githubusercontent.com/16433238/57427021-a0aca880-7254-11e9-8c5c-c4cc12a96a6f.png)

Ignore all exceptions:
![VD_L(N$LCO@EW`8BNX3$Y E](https://user-images.githubusercontent.com/16433238/57427066-d2be0a80-7254-11e9-91be-a5846e09c7c3.png)

Repeated F9 run program 
program crash
![MJ(U8U 4 QGHO1D@5_U~(`E](https://user-images.githubusercontent.com/16433238/57427080-e49fad80-7254-11e9-99be-1a8368c20d00.png)

the reason:
When I press f9 to continue running, the debugger first accepts the EXCEPTION_SINGLE_STEP of the next instruction of the breakpoint, and then continues to run.

![KM0C8VEY}$ACXV{C@UG3B03](https://user-images.githubusercontent.com/16433238/57427229-9343ee00-7255-11e9-9cdd-33a7b80f50fb.png)

The tf of the previous breakpoint has not yet entered, and another breakpoint is interrupted. Then the TF of the previous breakpoint is considered an illegal exception to be handed over to the application for processing, and the program crashes.

**Comment by flarejune** [comment] 2019-05-10 03:00
Thread concurrency,This bug always exists.To avoid this bug, use hardware breakpoints.

**Comment by mrexodia** [comment] 2019-05-12 11:56
Unfortunately hardware breakpoints do not solve this issue iirc.

Anyway, closing this issue as a duplicate of #1764. Your explanation is really good though so it's very useful thanks :)

**Closed by mrexodia** 2019-05-12 11:56 UTC

**Comment by ShiaoQuR** [comment] 2022-02-28 07:25
> Unfortunately hardware breakpoints do not solve this issue iirc.
> 
> Anyway, closing this issue as a duplicate of #1764. Your explanation is really good though so it's very useful thanks :)

If the code is reentrant, hardware breakpoint + exception filters may be a mitigation.
Let the debugger handles the exceptions and "do not break" when EXCEPTION_SINGLE_STEP(80000004) is triggered.

**Comment by mrexodia** [comment] 2022-02-28 09:32
The problem is that once you remove the hardware breakpoint to step over the instruction you immediately create a race condition (because other threads can start running).

**Comment by ShiaoQuR** [comment] 2022-02-28 13:32
Yeah...I mean this method somehow reduces the probability (the filter performs like a buffer). It didn't solve the problem.

Looks like .bpsync suspends all other threads, and marks them as "frozen" for debugger (https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/controlling-processes-and-threads). Is it possible to temporarily ignore events from another threads until they defrost?
