### ISSUE TITLE
Crash on certain input files

### ISSUE THREAD

**Issue by mrexodia** [x64dbg/x64dbg#2105] opened 2019-01-20 19:51 UTC
ping @Mattiwatti 

Some time ago I got a [sample](https://github.com/x64dbg/x64dbg/files/2776969/x64dbg-vuln.zip) that will crash when loading it into x64dbg. The reason appears to be that `RtlImageDirectoryEntryToData` returns a garbage pointer. Probably the best solution is to rewrite those functions, or perform the same check as the loader does in order to reject the result.

**Comment by mrexodia** [comment] 2019-01-20 19:55
Another report here, probably a similar issue but I didn't try yet... https://twitter.com/AGertani/status/1085900976039571457

**Comment by mrexodia** [comment] 2019-01-20 22:47
I 'fixed' this issue in 7d53b1ae08814665405e84bf39d0a016ab911df5, but just by wrapping the code in a try/except block... feels bad

**Comment by calshannon** [comment] 2019-01-20 22:53
Why am I subscribed to this?

**Comment by mrexodia** [comment] 2019-01-21 01:40
The export directory for the attachment :)

**Comment by Mattiwatti** [comment] 2019-01-21 23:14
OK, I found the cause, it was a fairly straightforward `dirSize > imageSize` case and the directory pointer was being dereferenced without checking if that was the case. Essentially the same thing that was already fixed for the debug directory previously. Made a PR.

I do still get this though, but only when debugging from VS, and if I ignore the AVs everything works fine:
![crash](https://i.imgur.com/iPjgxek.png)

No problems when debugging the exe straight or debugging x32dbg and then debugging the exe in the second instance.

I can't download the malware sample from VirusTotal btw, any chance you could check that? I tried downloading it in two different browsers but I just get forwarded to the homepage.

**Comment by mrexodia** [comment] 2019-01-21 23:21
Yeah the first sample is pretty straightforward, I started fixing it by
introducing some CheckedPtr<T> magic class but then I realized that it
would only cause complex stuff and make the code more unreadable so I opted
for a try/catch approach like the loader :)

I’ll attach that malware sample, I managed to download it yesterday from
some other website...

**Comment by Mattiwatti** [comment] 2019-01-21 23:21
Oh yeah, w.r.t. `try/except`... according to my 'sources' if you catch my drift, ntdll does indeed wrap access to at least the export directory in `LdrpGetProcedureAddress` in a `try`, but only with a `finally` to do some cleanup. So in this case it would return an uninitialized `NTSTATUS` value! Keep in mind that my, erm, guesses re: this, are from very old Windows versions so this is likely fixed by now. But yeah, `try/except` doesn't seem such a bad idea.

**Closed** 2019-03-17 18:46 UTC
Labels: bug
