### ISSUE TITLE
About Get qword ds:[address] question!!!!

### ISSUE THREAD

**Issue by nt47** [x64dbg/x64dbg#827] opened 2016-07-08 09:59 UTC
hi master:
![qq 20160708175401](https://cloud.githubusercontent.com/assets/6474298/16684011/32df4b68-4535-11e6-9e54-715211691576.png)
![qq 20160708175415](https://cloud.githubusercontent.com/assets/6474298/16684010/32dd821a-4535-11e6-9dc6-72050464fa0b.png)

i want to get address by editing,but i just get like this rip+offset ???
would u make it ez to trans ??? how about making it like od's ?

你好，我想在编辑的时候就得到变量地址，但是得到的确实RIP+偏移
能不能做的像OD一样

**Comment by wk-952** [comment] 2016-07-08 10:17
similar to #434

**Comment by nt47** [comment] 2016-07-08 11:13
@wk-952 didn't solve
https://discord.gg/MBHmRS4
plz

**Comment by mrexodia** [comment] 2016-07-09 03:17
So basically you want an option to display rip-relative instructions as `[rip + XXX]`?

**Comment by nt47** [comment] 2016-07-09 11:16
@mrexodia  no no no
i think i just want to get address when i edit asm rather than getting  rip+xxx
mb u can add a option 4 it. 
and i even dont't understand what rip+xxxx is 
rip+xxxx=ds:[var]  ??? really ?
ty

**Comment by mrexodia** [comment] 2016-07-09 11:17
Yes it's 64 bit addressing but in that case it's a duplicate of the issue
wk mentioned.

**Comment by nt47** [comment] 2016-07-09 11:37
@mrexodia but current version cant trans rip+xxxx to address
i get it need use alt+ins  in  memory window
would u add this feature ?
urge demand!!!

**Comment by mrexodia** [comment] 2016-07-09 11:39
I have absolutely no motivation to fix this right now, wait for #434 to be closed.

**Comment by nt47** [comment] 2016-07-10 08:32
@mrexodia 
nvm 
ty

**Comment by mrexodia** [comment] 2016-09-09 07:33
Has been solved.

**Closed by mrexodia** 2016-09-09 07:33 UTC
Labels: easy, enhancement, gui
