### ISSUE TITLE
Add Ability to Customize Elements from menu->registers

### ISSUE THREAD

**Issue by Z4ee** [x64dbg/x64dbg#3166] opened 2023-08-09 04:29 UTC
### Feature type

Quality of life, Debugging

### Describe the feature

I hope this finds you well. I am writing to propose a new feature that would significantly enhance the usability of x64dbg.
In the current version, there is no easy way to remove specific elements from the 'menu->registers' section.

![image](https://github.com/x64dbg/x64dbg/assets/113752393/15339bec-6a00-4c7e-86e1-d83c3450ed6f)

I appreciate your consideration of this feature request and look forward to hearing your thoughts on its potential inclusion in a future update.

Thank you for your ongoing commitment to making x64dbg a powerful and user-friendly tool.

**Comment by mrexodia** [comment] 2023-08-15 07:40
The reason is that the `CPURegistersView` doesn't use the `MenuBuilder` class. This is a duplicate of #1155

**Closed by mrexodia** 2023-08-15 07:40 UTC
Labels: feature, gui, good first issue
