### ISSUE TITLE
Source View code not showing since after snapshot 2016-05-16

### ISSUE THREAD

**Issue by mrfearless** [x64dbg/x64dbg#664] opened 2016-05-25 11:31 UTC
I've only been able to check some of the snapshots to confirm that the source view doesn't show any code since after the 2016-05-16 snapshot - I don't have 17-20th to check/verify, the next snapshots i have are 21st, 23rd, 24th and 25th of May and source view doesn't show anything in this. Last version i have that does show source view code is 16th May.

**Comment by mrexodia** [comment] 2016-05-25 14:19
appears to be working fine here, do you have a sample exe?

![w](http://i.imgur.com/lpmm4fm.png)

**Comment by mrfearless** [comment] 2016-05-25 14:37
Attached is a sample exe compiled with debug information and pdb file included.
https://www.dropbox.com/s/3lfvqso16n4x8i7/WinBif_with_pdb.rar?dl=0

This is from the may 16th snapshot:
![winbif_x64dbg_may16](http://s20.postimg.org/iy44p8eot/winbif_x64dbg_may16.png)

And this from the 24th snapshot:
![winbif_x64dbg_may25](http://s20.postimg.org/dy6oha925/winbif_x64dbg_may25.png)

Both using the same exe and pdb file.

**Comment by mrexodia** [comment] 2016-05-25 14:57
okay, should be fixed.

**Closed by mrexodia** 2016-05-25 14:57 UTC
Labels: bug

**Comment by azartheen** [comment] 2018-04-30 09:00
how to add custom code in intermediate line..... and how to select list of code in assembly lang code.... if i copy the code "it will be an (mov esp,dword ptr:ss [ebp-18]).... i want to select these line like (mov esp, [ebp-0x18])....... through list of line....  IS THERE ANY WAY IN X64dbg OR ANY AVAILABLE PULGIN??????

**Comment by mrexodia** [comment] 2018-04-30 09:08
@azarteen please explain what you want with screenshots or try again because I have no idea what you want.

**Comment by azartheen** [comment] 2018-05-02 04:53
i want to merge the file.... by copy and paste the source code.... is there any way in x64dbg????

**Comment by torusrxxx** [comment] 2018-05-02 05:02
So you want to select part of source line. That's indeed not possible with x64dbg, But you open your source file in a text editor and then copy it anyway.

**Comment by JesseRMeyer** [comment] 2018-05-16 16:04
I have a C++ program built by clang-cl (-Od -Zi (or -Z7)) on Windows 7 x64 and x64dbg (snapshot_2018-04-05_00-33) displays an empty source code view. Is it broken?

**Comment by mrexodia** [comment] 2018-05-16 16:05
No, clang doesn’t output compatible pdb files.

**Comment by JesseRMeyer** [comment] 2018-05-16 16:13
Thanks for the extremely quick reply!

What PDB definition do you use? Clang's output is compatible with Visual Studio's Debugger ...

**Comment by mrexodia** [comment] 2018-05-16 16:15
Probably it is outputting stuff that the version of dbghelp that x64dbg uses doesn't understand. You can try the symbol refactor version from here https://github.com/x64dbg/x64dbg/pull/1820. Without executable and symbol file I cannot reproduce the issue though.

**Comment by JesseRMeyer** [comment] 2018-05-16 16:31
Here's a minimal repo exe / symbol .pdb file: https://drive.google.com/file/d/1YiXkYtqQVxiQvUV1vs1v7DSp3w-Yqa60/view?usp=sharing

Unfortunately I don't have the time to build and test the version with improved symbol detection, unless there is already a pre-built version. I checked but didn't see one.

**Comment by Debooch** [comment] 2018-05-16 16:32
Stop spamming

Op ma 30 apr. 2018 11:01 schreef Azar <notifications@github.com>:

**Comment by mrexodia** [comment] 2018-05-16 16:33
@JesseRMeyer with the improved symbol build it correctly detects the lines and symbols. Right now there is no pre-built version because there are conflicts with the development branch. If you don't want to build you will have to wait until those get fixed.

**Comment by JesseRMeyer** [comment] 2018-05-16 17:00
@mrexodia Thank you for investigating and verifying that for me. I'll wait until it is merged and stable.

**Comment by JesseRMeyer** [comment] 2018-05-17 14:35
I was able to temporarily work around this by switching from LLD to Microsoft's linker. I hope to use LLD again soon.

**Comment by mrexodia** [comment] 2018-05-17 15:17
The conflict should be resolved and you can try the symcache branch now.

**Comment by JesseRMeyer** [comment] 2018-05-17 16:28
I can confirm this works with LLD! Thank you for such an expedient resolution!

For general usage questions, where should I ask? Is the Gitter channel the place?

**Comment by mrexodia** [comment] 2018-05-17 16:30
Yeah Gitter is fine. All the chat groups are synced up anyway so feel free to use whatever platform you like most.

**Comment by mrexodia** [comment] 2018-11-14 20:33
If it works in Windbg/visual studio it should work in x64dbg.

**Comment by mitsukuri** [comment] 2018-11-14 21:04
Yep, my bad, was expecting the source to be loaded automatically while actually it is loaded via `open source file` from cpu view context menu, which works like a charm. Sorry for bothering and, using a chance, I'd like to thank you for this wonderful debugger!

**Comment by mrexodia** [comment] 2018-11-15 13:54
Good to hear your issue is resolved and you’re welcome :)

**Comment by betrayerx** [comment] 2019-01-31 21:13
Hello. I have such error 'Skipping PDB validation, expect invalid results!' with files, created in Visual Studio. Why??
And I dont see where is "open source file from cpu view context menu" 
Help me please, how to see source code??

**Comment by betrayerx** [comment] 2019-02-01 00:49
Sorry, all works! I am stupid, or this is local bug. I recompile code , and see all
