### ISSUE TITLE
mov r9b,1 is disassembled incorrectly

### ISSUE THREAD

**Issue by handoeilsen** [x64dbg/x64dbg#296] opened 2015-05-07 17:28 UTC
The following instruction:  mov r9b,1
Is being shown as:            mov cl,1
Bytes: 41 B1 01

**Comment by mrexodia** [comment] 2015-05-07 17:32
yea.. BeaEngine has a lot of bugs. We are currently migrating to capstone so then everything should be fine. Just tested it and capstone shows this:

![image](http://i.imgur.com/64shkN8.png)

**Comment by mrexodia** [comment] 2015-07-13 04:19
duplicate of #337

**Closed by mrexodia** 2015-07-13 04:19 UTC

**Comment by mrexodia** [comment] 2015-10-28 04:28
I checked and this issue has been resolved:

![screenshot](http://i.imgur.com/JekpM2E.png)
