### ISSUE TITLE
Execute till user code

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#256] opened 2015-04-12 19:44 UTC
It would be great to have "Execute till user code" (like "Olly"). Is it possible?
Thank you!

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/256
- Originally reported by: Anonymous
- Originally created at: 2015-02-22T10:52:30.685

**Comment by shinmai** [comment] 2015-09-23 10:04
Is this a duplicate of #80 or did I misunderstand the title?

**Closed** 2015-10-13 15:17 UTC
Labels: duplicate
