### ISSUE TITLE
bp _waccess bug?

### ISSUE THREAD

**Issue by nmweizi** [x64dbg/x64dbg#835] opened 2016-07-11 05:31 UTC
version  x64 snapshot Jul 9 2016
->   bp _waccess 
->   break  _waccess   in  **msvcrt.dll**
->   but i hope break _waccess in **msvcr100.dll**

**Comment by mrexodia** [comment] 2016-07-11 11:03
It's not a bug. It just takes the first api it finds. If you want to be
specific, use "msvcrt.dll:_waccess"

**Comment by nmweizi** [comment] 2016-07-11 13:52
![Uploading 2016-07-11_214612.jpg…]()

**Comment by mrexodia** [comment] 2016-07-11 20:36
It looks like you have an extra space after the `.` for me:

`bp msvcr120.dll:_waccess` works fine

**Comment by nmweizi** [comment] 2016-07-12 15:31
copy bp msvcr120.dll:_waccess
poster bp msvcr120.dll:_waccess
modify 120 -> 110

![8](https://cloud.githubusercontent.com/assets/1232444/16772986/c0d1049c-4888-11e6-9b6f-69d412de2091.jpg)

**Comment by wk-952** [comment] 2016-07-12 17:12
Confirmed here too, some examples:

1. `msvcrt.dll:_waccess`  vs  `msvcr120.dll:_waccess`
![er1](https://cloud.githubusercontent.com/assets/11916365/16776122/258deeb0-4864-11e6-9559-d51c3706d2b4.png)

2. `msvcrt.dll:_wctype`  vs  `msvcr120.dll:_wctype`
![er2](https://cloud.githubusercontent.com/assets/11916365/16776139/44083a6c-4864-11e6-8480-d0dba8bd742a.png)

3. `_LNan_C`  vs  `msvcr120._LNan_C`  vs  `msvcr120.dll:_LNan_C`
![er3](https://cloud.githubusercontent.com/assets/11916365/16776182/7fb53a56-4864-11e6-94a8-f8ebe086c653.png)

**Comment by nmweizi** [comment] 2016-07-14 04:23
Confirmed

**Comment by nmweizi** [comment] 2016-07-14 04:30
![Uploading 新建位图图像 (9).jpg…]()
![Uploading 新建位图图像 (10).jpg…]()

**Comment by mrexodia** [comment] 2016-07-14 13:51
Could you verify if these exports are in the symbols view?

**Comment by nmweizi** [comment] 2016-07-15 00:46
![11](https://cloud.githubusercontent.com/assets/1232444/16860208/5ae2440c-4a68-11e6-984a-2270ee0362d2.jpg)
   
Interfac Is Chinese

**Comment by torusrxxx** [comment] 2016-07-15 07:39
reproduced this problem. 我们将尽快修复这个问题，感谢您的反馈。

**Comment by nmweizi** [comment] 2016-07-16 13:48
use x64 snapshot Jul 9 2016
is ok.thinks

**Comment by mrexodia** [comment] 2016-07-16 14:42
Please close the issue once it's fixed.

Op za 16 jul. 2016 om 15:49 schreef nmweizi <notifications@github.com>:

**Closed** 2016-07-17 00:41 UTC
Labels: bug, not reproduced
