### ISSUE TITLE
x64Dbg Dump view doesn't allow to edit values as floats, doubles and hex.

### ISSUE THREAD

**Issue by KulaGGin** [x64dbg/x64dbg#2319] opened 2020-04-10 10:57 UTC
In Dump view when I make my values to show as floats and when I right click on it, then choose Modify Value, it doesn't allow me to edit it as a float:
![x64dbg_KuA2wHie2x](https://user-images.githubusercontent.com/16989713/78985966-cf9d5f80-7b32-11ea-8470-87f252aaed26.png)

Same with doubles and hex. I think it would make sense to add support to edit values in dump as most popular struct types: bool, byte, short, int, long, long long, float, double. And allow us edit integer values as hexadecimal and decimal values.

My x64Dbg version:
![x64dbg_ZnXeDJ6Eg0](https://user-images.githubusercontent.com/16989713/78985884-8c42f100-7b32-11ea-8ea0-6691a74035e8.png)

I use Windows 10 x64 1709:
![winver_ejKTw3maLO](https://user-images.githubusercontent.com/16989713/78985919-a4b30b80-7b32-11ea-8fe5-68be2198c493.png)

**Comment by mrexodia** [comment] 2020-06-07 15:51
Duplicate of #1550

**Closed by mrexodia** 2020-06-07 15:51 UTC
