### ISSUE TITLE
new menu item for non system modules

### ISSUE THREAD

**Issue by wj5449** [x64dbg/x64dbg#2786] opened 2021-11-16 09:32 UTC
### Feature type

Debugging, Other

### Describe the feature

use case :  when i want search for a const value ,i only want to seacrch from user modules, 
reason :     it may be more useable for users
end:          that's all 
                     thanks for you time

**Comment by torusrxxx** [comment] 2021-11-20 08:46
Duplicate of a 4-year old easy issue #1461

**Closed by torusrxxx** 2021-11-20 08:46 UTC
Labels: feature
