### ISSUE TITLE
Attach - the content entered in the search will disappear when it is refreshed

### ISSUE THREAD

**Issue by cn-fairy** [x64dbg/x64dbg#2687] opened 2021-07-16 08:07 UTC
Version:snapshot_2021-07-01_23-17
System:Win10 10.0.19042

Confusion: The content entered in Attach-Search disappears when it is refreshed
Result: need to re-enter the content to be searched
The following motion picture shows：
![2](https://user-images.githubusercontent.com/74580422/125914404-fb4d5fb5-230e-41d4-b062-d608177135cf.gif)

**Comment by torusrxxx** [comment] 2021-07-19 12:32
duplicate of #2317

**Closed by torusrxxx** 2021-07-19 12:32 UTC
