### ISSUE TITLE
Column's reset on each launch

### ISSUE THREAD

**Issue by Archer-Dante** [x64dbg/x64dbg#630] opened 2016-04-21 02:48 UTC
Columns position has no saves
Each program's launch all columns positions in whole gui just resets (dump, registers, stack, disassembly view). That makes me drag'n'drop it again and again.
demo: http://i.imgur.com/gAWHPEZ.gif

**Comment by mrexodia** [comment] 2016-04-21 02:53
duplicate of #368

**Closed by mrexodia** 2016-04-21 02:53 UTC
