### ISSUE TITLE
是否考虑在栈窗口显示api参数？

### ISSUE THREAD

**Issue by MrXiao7** [x64dbg/x64dbg#3066] opened 2023-04-10 16:25 UTC
类似od那样
![image](https://user-images.githubusercontent.com/5705426/230945660-24ad4be2-571e-4c50-8bce-6c2cb15a28d3.png)

**Comment by zzfeed** [comment] 2023-04-12 08:28
Do you consider displaying api parameters in the stack window?

**Comment by mrexodia** [comment] 2023-04-14 17:56
Duplicate of #2533

**Closed by mrexodia** 2023-04-14 17:56 UTC
