### ISSUE TITLE
movsxd rax, dword ptr ds:[rbx+1] is disassembled incorrectly

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#208] opened 2015-04-12 18:46 UTC
The following instruction:

    movsxd rax,dword ptr ds:[rbx+1]

Is being shown as:

    movsxd rax,qword ptr ds:[rbx+1]

Notice the **qword**. Bytes: `48 63 43 01`.

Perhaps it's a bug of BeaEngine, but I'm not sure.

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/208
- Originally reported by: [RaMMicHaeL](http://bitbucket.org/RaMMicHaeL)
- Originally created at: 2014-09-27T19:24:16.267

**Comment by Nukem9** [comment] 2015-04-12 18:47
Hi,

Yep, it's definitely a BeaEngine bug. Hopefully this will be fixed once we switch to Capstone.

----------------------------------------
Original comment by: [mrexodia](http://bitbucket.org/mrexodia)

**Comment by Nukem9** [comment] 2015-04-12 18:47
Nice. I did not know Captone yet. Seems very promising. Maybe we should wrap the results from the disassembler, something like enhanced "basic_info" structure.

----------------------------------------
Original comment by: tr4ceflow .com

**Comment by mrexodia** [comment] 2015-07-13 04:19
duplicate of #337

**Closed by mrexodia** 2015-07-13 04:19 UTC

**Comment by mrexodia** [comment] 2015-10-28 04:28
I checked and this issue has been resolved:

![screenshot](http://i.imgur.com/JekpM2E.png)
