### ISSUE TITLE
x64dbg.exe hangs when pressing Cancel in "Go to expression" window

### ISSUE THREAD

**Issue by deselect** [x64dbg/x64dbg#310] opened 2015-05-30 11:07 UTC
1. I have started x64dbg.exe
2. Opened iexplore.exe (x64 version)
3. Pressed Ctrl+G in CPU tab.
4. Typed three characters which could not be interpreted as address ("123" and "abc" - works good, it does not hang, "ghi" and "nta" both result in hanging)
5. Pressed "Cancel" button. x64dbg hangs.

OS - Windows 7 Professional; x64dbg started at medium integrity level.

**Comment by Nukem9** [comment] 2015-05-30 20:48
Unable to reproduce (although I use Win8). Are you using the latest snapshot?

**Comment by deselect** [comment] 2015-05-30 22:50
Yes, I am using latest snapshot (27 May 2015). Try W7 Professional.

**Comment by Nukem9** [comment] 2015-05-31 00:09
Weird. I'll install Windows 7 on a virtual machine later to check it.

**Comment by ApertureSecurity** [comment] 2015-05-31 00:12
I can check right now and save you some time Nukem.

**Comment by ApertureSecurity** [comment] 2015-05-31 00:38
I don't have the x64 bit version on this pc . I can check in 30 minutes.

**Comment by ApertureSecurity** [comment] 2015-05-31 01:48
I haven't been able to replicate this issue. I followed along with the video and no problems whatsoever.

**Comment by deselect** [comment] 2015-05-31 10:16
Weird. Tested on another PC with Windows 7 Home Basic. It does not hang after first pressing "Cancel", but I tried it some more times (typing and pressing "Cancel"), so it hangs.

On my PC it always hangs after first "Cancel".

**Comment by Nukem9** [comment] 2015-05-31 18:26
It almost sounds like a threading issue. I know that a background thread runs when you type something (searching for symbols, might cause a lock), but i'm still unable to reproduce it. I've tried it many times now.

**Comment by deselect** [comment] 2015-05-31 20:36
I can give you access with TeamViewer, for example.

**Comment by AVJoKe** [comment] 2015-06-01 06:40
@deselect 
Do you have a multi-core CPU ( or a VM with > 1 core )?

I managed to reproduce it in a Win7 VM with one core. 

![capture](https://cloud.githubusercontent.com/assets/11389175/7907455/bf1b5188-0839-11e5-856b-da1373f61119.PNG)

**Comment by deselect** [comment] 2015-06-01 10:30
I have one-core CPU. But I tried it on another PC with multi-core CPU too, and it did not hang after first "Cancel", but when I tried it many times it hung.

**Comment by Nukem9** [comment] 2015-06-06 17:56
The only reason I can think of this happening is because of `mValidateThread->terminate();` The thread might be running in the background, but then is terminated in the middle of a function, leaving random bugs.

I still can't get it to crash (1 cpu core allocated, underclocked to 2.0GHz). @mrexodia any idea?

**Comment by mrexodia** [comment] 2015-06-06 20:26
should be fixed, so for now a duplicate of #312

**Closed by mrexodia** 2015-06-06 20:26 UTC
