### ISSUE TITLE
ARM support?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [x64dbg/x64dbg#523] opened 2016-02-03 14:07 UTC
I guess that is not supporting that since I didn't found it wrote anywhere.

Are you planning to support it?

Thanks!

**Comment by XVilka** [comment] 2016-02-03 15:59
Easy to solve, if use radare2 as a backend

**Comment by mrexodia** [comment] 2016-02-05 02:57
At the moment there are no plans for ARM support. The GUI should be pretty
much compilable on Linux so if anyone is interested you can use r2 and make
it work with anything.

**Comment by mrexodia** [comment] 2016-09-07 07:03
duplicate of #606

**Closed by mrexodia** 2016-09-07 07:03 UTC
Labels: feature

**Comment by E3V3A** [comment] 2018-10-31 16:31
@XVilka 
How do you add r2 as backend?

**Comment by SaidTorres3** [comment] 2024-05-21 18:54
what about now

**Comment by mrexodia** [comment] 2024-05-21 19:12
Still the same. The GUI is fairly cross-platform, so porting to ARM64 on Windows shouldn’t be _that_ much work. Personally I don’t have much interest though…
