### ISSUE TITLE
Add windows manager of debugged app

### ISSUE THREAD

**Issue by ThunderCls** [x64dbg/x64dbg#1075] opened 2016-09-10 07:17 UTC
Any chance of getting something like this for the app being debugged ? 

![captura1](https://cloud.githubusercontent.com/assets/13303069/18408718/cc76dbb4-7704-11e6-99c3-8232ff5f5ab8.PNG)

Or even going further and allow it to modify /play with each window property like title, style, etc

**Comment by mrexodia** [comment] 2016-09-10 07:18
In my opinion this should be a plugin, but if there is anything you need for the API, don't hesitate to ask.

**Comment by ThunderCls** [comment] 2016-09-10 07:38
Let's see if I can come up with something ;)

**Comment by mrexodia** [comment] 2016-11-18 20:54
duplicate of #989

**Closed by mrexodia** 2016-11-18 20:54 UTC
Labels: feature, fun
