### ISSUE TITLE
Conditional breakpoint breaks always

### ISSUE THREAD

**Issue by tbytedev** [x64dbg/x64dbg#2253] opened 2019-11-21 16:02 UTC
I would like to set up a conditional breakpoint. If the condition evaluates true, the code breaks with int3, and that's fine. If the condition is false it also breaks, but this time with exception 80000003 (EXCEPTION_BREAKPOINT). What I'm trying to achieve is not to break or throw exception if my condition is false. Is there a way to do that? If I disable the breakpoint, it doesn't throw exceptions, just runs fine, so the exception has to do with the conditional breakpoint.

This is my breakpoint setup:
var $dh_inmap
var $dh_nobreak
var $dh_rth
bp 0x7ffcf89a8b10, OnWait
bpcnd 0x7ffcf89a8b10, $dh_inmap == 1 && $dh_nobreak == 0 && $dh_rth == tid()

I don't want to ignore EXCEPTION_BREAKPOINT, because I will need it later.
It looks like that $breakpointexceptionaddress is initially set to the program entry point, and I don't change afterwards.

**Comment by mrexodia** [comment] 2020-01-16 14:01
Unfortunately a duplicate of #1764, which has no solution (on a technical level) so far.

**Closed by mrexodia** 2020-01-16 14:01 UTC
Labels: bug
