### ISSUE TITLE
Buggy memory BP

### ISSUE THREAD

**Issue by Klanly** [x64dbg/x64dbg#2024] opened 2018-09-11 01:05 UTC
Some stupid app which has a very huge memory page (1GB+) make x64dbg crash itself when setting memory bp on such page.

https://i.imgur.com/m7Ykw4u.jpg

PLEASE make memory bp size corresponds to ACTUAL selection in dump window (I mean mod upper/lower bound by 0x1000).

I think these lines cause the problem.
duint base = MemFindBaseAddr(addr, &size, true);  //why both DUMPs and memory map panel go here????
.....
738	     if(!SetMemoryBPXEx(base, size, type, restore, (void*)cbMemoryBreakpoint))

version: latest, membp is unusable for years.
os: win10

**Comment by mrexodia** [comment] 2018-10-01 13:20
Closed as duplicate of #1513 this is a much requested feature, but I don't use it so nothing is happening. To support memory breakpoints we have to switch to [GleeBug](https://github.com/x64dbg/GleeBug).

**Closed by mrexodia** 2018-10-01 13:20 UTC
