### ISSUE TITLE
Is there a way to search for a sequence of command lines?

### ISSUE THREAD

**Issue by Cen-Silver** [x64dbg/x64dbg#2260] opened 2019-12-03 14:18 UTC
I'm somewhat new to all this reverse engineering stuff, and x64dbg seems pretty nice, but right now I'm going insane trying to find how the hell can I find for a sequence of commands, with wildcards too.
I know the search for "String References" works for finding commands, but even with it I still didn't figure out how to search more than one line of command nor what it uses for wildcards (Assuming it supports them at all)

Like, say if I'm trying to find

mov eax,05
cmp rbx,20

But I can't tell that the register "rbx", in this occasion, will be rbx.

So how could I locate that sequence?!?

I tried "?" and "*" already, and neither seemed to work... help..?

[PS: using 26|11|2019 version, Win10 x64Bits]

**Comment by mrexodia** [comment] 2020-01-16 14:07
Duplicate of #779

**Closed by mrexodia** 2020-01-16 14:07 UTC
