### ISSUE TITLE
Scylla dump bad file with latest x64dbg

### ISSUE THREAD

**Issue by sst311212** [x64dbg/x64dbg#1425] opened 2017-01-18 10:29 UTC
It dump bad file, even no icon, when I use latest x64dbg(x32).
But it's fine in 20161225 version.

**Comment by mrexodia** [comment] 2017-01-18 13:34
Could you give exact reproduction steps, including OS version and a binary? This makes it easier for us to reproduce the issue.

**Comment by sst311212** [comment] 2017-01-18 16:55
I debug this file [MegabytePunch.zip](https://github.com/x64dbg/x64dbg/files/714451/MegabytePunch.zip).
Just dump file at original OEP.
Platform: Windows 10 Pro x64 1607

**Comment by skillax** [comment] 2017-01-18 22:56
I've noticed this too. The last 'working' build was 2016-12-29'; the 2017-01-02 build and all afterwards create corrupted dump files. Tested on Win 8.1 x64 on multiple unprotected and non-packed x86 targets (to ensure it was no human error).   I ran all the different snapshots 'virgin' as they are downloaded, not overwriting my existing x64dbg and not changing any of the default x64dbg or Scylla settings before dumping (I did verify if all the settings were the same too) 

After dumping the executables fail with the message "The application has failed to start because it's side-by-side configuration is corrupt".  Trying to load the dumped and rebuilded executables into x64dbg fails with "CreateProcess failed: ERROR_SXS_CANT_GEN_ACTCX" as well (= same error).

I ran sxstrace.exe on those corrupted executables (built-in Windows tool) and the raw error is something like 'Cannot read Manifest file. Invalid XML on line 0.'.   Using the 2017-12-29 snapshot dumping work just fine.    The most obvious and visible indicator:  the corrupted dumps of these non-protected test-targets don't show their icon in Windows Explorer either dumping. 

Also tried all kinds of settings within Scylla, including running x64dbg as admin or not; but it doesn't make a difference in this aspect .   You can download my test-set to compare the results yourself here: https://we.tl/JSjVDsWho1

The test.exe is the original executable (it's the free and unprotected NirLauncher.exe tool simply renamed), test_dumped_2016-12-29.exe is the working dump and test_dumped_2017-01-02.exe is the 'corrupted' dump.   I'm pretty confident it's some newly introduced bug :)

**Comment by gmastergreatee** [comment] 2017-01-19 19:03
Maybe related 
https://github.com/NtQuery/Scylla/issues/44
https://github.com/NtQuery/Scylla/issues/43

**Comment by wk-952** [comment] 2017-01-20 15:14
Seems to fixed in latest snapshot `snapshot_2017-01-19_21-26`

**Comment by mrexodia** [comment] 2017-01-21 14:34
I was testing on an older version for quite some time but it indeed solved now.

**Closed by mrexodia** 2017-01-21 14:34 UTC
Labels: bug, not reproduced
