### ISSUE TITLE
Unable to delete comment

### ISSUE THREAD

**Issue by caomfan** [x64dbg/x64dbg#2409] opened 2020-07-28 09:59 UTC
- Debugger version: Jun 22 2020, 14:18:43.
- Operating system version: Windows 10 1903

**Comment by mrexodia** [comment] 2020-07-29 20:22
I cannot reproduce this, can you give reproduction steps?

**Comment by caomfan** [comment] 2020-07-30 02:11
Ctrl+Alt+C,In this window, the comment cannot be refreshed immediately after deleting it, in fact it has been deleted

**Comment by torusrxxx** [comment] 2020-07-30 15:20
Duplicate of #999

**Closed by torusrxxx** 2020-07-30 15:20 UTC
Labels: bug, not reproduced
