### ISSUE TITLE
Mapped Shortcuts Do Not Match Keys Pressed

### ISSUE THREAD

**Issue by connah0047** [x64dbg/x64dbg#2176] opened 2019-05-17 03:48 UTC
- Version: May 9, 2019
- Windows 7 Professional, SP1, x64
- When customizing shortcuts, some keys pressed do not correspond to the keys mapped

**Steps to Reproduce:**
1) Start x32dbg
2) Click on Options -> Shortcuts
3) Scroll down to the instruction "Debug -> Step Into" and click once on it
4) Click the "Clear" button to clear the default shortcut of "F7"
5) Click in the "Shortcut" box and press the "F7" key on the keyboard in an attempt to set the shortcut back to "F7"
6) Observe that "Shift+F6" appears in both the "Shortcut" box and under the "Shortcut" column instead of the expected "F7". There is no readily apparent way to reset it back to default values or to configure "F7" for use as a shortcut now. "F7" is not the only problem key as shown immediately below.

Other keys that reproduce this problem and the errant shortcuts they map to:
F3 maps as Shift+F2
F4 maps as Shift+F2
F8 maps as Shift+F6
F11 maps as Shift+F10
F12 maps as Shift+F10
Scroll Lock maps as Shift+NumLock
Insert maps as Shift+Enter
Page Up maps as Shift+Down
Page Down maps as Shift+Down
Delete maps as Shift+Enter
Up Arrow maps as Shift+End
Left Arrow maps as Shift+End

In an attempt to resolve this issue myself, I have tried:

1) Searching the  bug tracker for similar issues
2) Clearing ALL existing shortcuts before trying to map a problem shortcut
3) Downloading and running a freshly installed copy without making any changes or customizations apart from trying to map a shortcut key

**_PLEASE NOTE:_** This is my first bug report and I have done my very best to make sure it adheres to specifications and that there was not a pre-existing bug describing my problem. If I have overlooked something, please forgive me and point me in the right direction. Thank you!

**Comment by kdma** [comment] 2019-05-18 14:32
I am no mantainer but looks like this is the problem https://github.com/x64dbg/x64dbg/blob/development/src/gui/Src/BasicView/ShortcutEdit.cpp#L67-L68
For example with F7
Qt::Key_Backtab | 0x01000002
Qt::Key_F7 |          0x01000036
Since F7 "contains" Backtab (which I never heard of) it replaces that part with shift tab and it goes haywire. I am not sure what is the rationale for that substitution.

**Comment by connah0047** [comment] 2019-05-18 16:18
I have a feeling I'm about to ask a really dumb question, but what is a "Backtab"? I've never heard of that before. Moreover, I don't see anything in the ShortcutEdit.cpp code that would allow F5, F6, and F7 to work, but not F4 or F8, for example. I keep having this sneaking suspicion that I'm doing something wrong because this seems way too obvious of a bug for it to have been around all this time and me just happen to be the first person to find and report it.

Are you able to reproduce this problem on your end? I'd just like to know if others are having this trouble too. Thanks again for your time!

**Comment by kdma** [comment] 2019-05-18 16:44
About the backtab no idea, I never heard of it and yes the problem is reproducible. 
Regarding the keys that reproduce the bug just look the keycode for the keys here:
https://doc.qt.io/qt-5/qt.html#Key-enum 
Calculate the bitwise AND like in the previous code snippet and see that for those key that start with 0x1 and end with 0b1X the result will be always the keycode for the Backtab and that means that the if body gets evaluated.

**Comment by connah0047** [comment] 2019-05-18 17:07
Perfect, thank you! I had missed that initially! I think you absolutely found the bug. Hopefully the developers will have a look into this soon. Seems like it would be an easy fix. (Says the keyboard warrior.) :)

**Comment by kdma** [comment] 2019-05-18 17:16
Just wait for any of the maintainers to chime in about the rationale of the backtab substitution and make your first pull request.

**Comment by mrexodia** [comment] 2019-05-18 22:36
I don’t remember this, so go ahead with whatever fixes you deem necessary.

**Comment by mrexodia** [comment] 2019-06-15 16:37
Was this actually fixed?

**Comment by connah0047** [comment] 2019-06-17 04:23
I have not been able to personally address this. This is my first time
attempting to contribute Qt code via GitHub and I have had significant
issues getting the needed software installed and properly configured in
order to make the necessary changes.

**Comment by mrexodia** [comment] 2019-06-17 20:54
It's been fixed in #2189, thanks to @kdma!

**Comment by connah0047** [comment] 2019-06-18 12:29
BEAUTIFUL! Thank you all so much!

**Closed** 2019-06-18 22:17 UTC
Labels: bug, not reproduced

**Comment by Setaran** [comment] 2020-03-23 08:58
Hello
I want to make a shortcut for:
View -> Previous Tab
When I hit `Ctrl+Shift+Tab`
It becomes `Ctrl+Shift+Backtab` instead.
And it does not work.
How can I tell the program not to use Backtab, and use Tab?

Note:
View -> Next Tab and my other shortcuts work just fine.
