### ISSUE TITLE
Random crashes (Patches dialogue + invalid param to CRT function)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#761] opened 2016-06-17 20:53 UTC
Was debugging for some time, and encountered 2 or 3 crashes.

After some hours of debugging i restarted the target and suddenly the debugger crashed with the error `invalid parameter passed to CRT function`.

Another crash related to the patches dialogue (`Ctrl + P`), after editing some values in a data section (non-executable data section) i wanted to restore them back, so upon selecting them in the patches dialogue (just single click on them) the debugger crashed.

No reproduction steps since these were very random, and i couldn't trigger/reproduce them again, sorry about that, but luckily the debugger generated minidumps.

minidumps:
http://rgho.st/private/6j7Wbnzws/7b5520df36058feabae9ce3909615331
Password: `asd123`

Using `snapshot_2016-06-15_02-16.7z`
OS: Win10 x64

**Comment by Nukem9** [comment] 2016-06-17 21:04
Patch dialog crash @ https://github.com/x64dbg/x64dbg/blob/development/src/gui/Src/Gui/PatchDialog.cpp#L50
Invalid CRT function @ https://github.com/x64dbg/x64dbg/blob/development/src/dbg/_exports.cpp#L1070

CRT is related to #731 because the string needs to be truncated.

**Comment by mrexodia** [comment] 2016-06-18 10:48
Thanks a lot for that, saves me WinDBG hell 😄 anyway that crash in PatchDialog.cpp is really strange

**Comment by wk-952** [comment] 2016-06-18 11:54
It seems that the patches window issue is triggered when re-enabling the patches
1. Debug anything
2. Change any instruction at any section, then press `Ctrl + P` to open the patches dialogue
3. Disable the patches by deselecting them
4. Again re-enable the patches and the debugger will crash

Sometimes you have to repeat steps 3 & 4 to trigger the issue.

**Comment by Treetippayanipa** [comment] 2016-06-19 00:10
IssueReport

**Comment by wk-952** [comment] 2016-06-19 00:15
@Treetippayanipa you okay there buddy ?

**Comment by mrexodia** [comment] 2016-06-19 00:46
Ehm maybe we have bots?

**Comment by wk-952** [comment] 2016-06-19 00:51
I guess, take a look at [#760 (comment)] (https://github.com/x64dbg/x64dbg/issues/760#issuecomment-226971945)

**Comment by Treetippayanipa** [comment] 2016-06-19 00:57
IssueReport

**Comment by Nukem9** [comment] 2016-06-19 01:23
It's not a bot, GitHub's issue tracker is (ironically) broken on certain browsers.

If you look at the html source:
```
class="form-control input-contrast comment-form-textarea js-comment-field js-improved-comment-field js-task-list-field js-quick-submit js-size-to-fit js-suggester-field js-quote-selection-target js-session-resumable"
              >IssueReport</textarea>
```

**Comment by mrexodia** [comment] 2016-06-19 21:10
Hm so github notifications appear to be broken too, I'm not getting emails...

**Comment by mrexodia** [comment] 2016-06-24 02:00
Should be fixed now, couldn't reproduce that crash with strings though...

**Closed** 2016-06-24 02:00 UTC
Labels: bug, priority
