### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by GNIR33NIGN3** [x64dbg/x64dbg#727] opened 2016-06-06 23:08 UTC
As mentioned [here](https://forum.tuts4you.com/topic/38266-x64-dbg-comments/), I would like to submit a request for advanced comments, similar to Olly. Here is an image showing the advanced comments:

http://i.stack.imgur.com/e0sUW.png

Thanks!

**Comment by mrexodia** [comment] 2016-06-06 23:11
duplicate of #334

**Closed by mrexodia** 2016-06-06 23:11 UTC
