### ISSUE TITLE
View of Debugee's open handles

### ISSUE THREAD

**Issue by havokeachday** [x64dbg/x64dbg#587] opened 2016-03-01 03:15 UTC
Similar to ProcessExplorer's handles view. Object specific decorators could be useful as well for displayed handles, such as registry key contents, file contents, or for things such as memory mapped files, a quick way to view the mapped memory would be nice as well.

**Comment by mrexodia** [comment] 2016-03-02 13:18
duplicate of #79

**Closed by mrexodia** 2016-03-02 13:18 UTC
