### ISSUE TITLE
Handles

### ISSUE THREAD

**Issue by cobrce** [x64dbg/x64dbg#624] opened 2016-04-12 18:57 UTC
is it possible to add a windows that shows handle (if the feature already exists tell me where to find it) and to show it's value API parameters, like when I put a BP in ReadFile shows the file path next to handle value

**Comment by mrexodia** [comment] 2016-04-12 19:02
Hello, Could you make separate issues for each request? This is kind of
confusing since some are duplicate and some are not going to be implemented.

**Comment by cobrce** [comment] 2016-04-12 19:37
done

**Comment by mrexodia** [comment] 2016-05-23 02:36
duplicate of #79

**Closed by mrexodia** 2016-05-23 02:36 UTC
Labels: feature
