### ISSUE TITLE
Memory leak and heavy CPU load when working with symbols

### ISSUE THREAD

**Issue by deselect** [x64dbg/x64dbg#903] opened 2016-07-30 16:21 UTC
1. Open Internet Explorer or attach to it.
2. Type "symdownload mshtml" and "symdownload ieframe" to download symbols for some huge IE libs.
3. Open ieframe or mshtml in Symbols tab. Try some searching of symbols, add some breakpoints.
4. Do some debugging.
5. It becomes impossible to work with debugger due to huge (> 1gb) memory leak and a heavy CPU load.

**Comment by mrexodia** [comment] 2016-07-30 19:03
memory leak should be fixed, performance is duplicate of #747

**Closed by mrexodia** 2016-07-30 19:03 UTC
Labels: bug
