### ISSUE TITLE
Failed to load PDB for chrome.exe.pdb and chrome.dll.pdb

### ISSUE THREAD

**Issue by marunguy** [x64dbg/x64dbg#3464] opened 2024-10-30 06:49 UTC
### Operating System

Windows 11 Home, 22631.4317

### x64dbg Version

Oct 18 2024

### Describe the issue

Failed to load PDB for chrome.exe.pdb, chrome.dll.pdb and chrome_elf.pdb
I tried loading the chrome.exe pdb by referring to the following link.
* https://www.chromium.org/developers/how-tos/debugging-on-windows/
* `Option -> Preferences -> Misc` menu
  * `Symbol Store`: https://chromium-browser-symsrv.commondatastorage.googleapis.com

The download of chrome.exe.pdb was successful, but loading the symbols failed.
```
Downloading symbol chrome.exe.pdb
  Signature: B15964EE71F0B5E24C4C44205044422E1
  Destination: d:\symbols\chrome.exe.pdb\B15964EE71F0B5E24C4C44205044422E1\chrome.exe.pdb
  URL: https://chromium-browser-symsrv.commondatastorage.googleapis.com/chrome.exe.pdb/B15964EE71F0B5E24C4C44205044422E1/chrome.exe.pdb
Finished downloading symbol chrome.exe.pdb in 5.734s
PDB uses an obsolete format.
[DIA] Failed to load PDB: d:\symbols\chrome.exe.pdb\B15964EE71F0B5E24C4C44205044422E1\chrome.exe.pdb
No symbols loaded for: chrome.exe
```
chrome.dll.pdb and chrome_elf.pdb also have the same problem.

In windbg, the chrome.exe.pdb symbol is loaded properly.
```
0:040> lm
start             end                 module name
00007ff7`548d0000 00007ff7`54b97000   chrome_exe   (private pdb symbols)  d:\symbols\chrome.exe.pdb\B15964EE71F0B5E24C4C44205044422E1\chrome.exe.pdb
00007ff8`90ed0000 00007ff8`9f69c000   chrome     (deferred)             
...
...
0:040> x /D /f chrome_exe!a*
 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z

00007ff7`549841b0 chrome_exe!absl::inlined_vector_internal::Storage<base::sequence_manager::Task,8,std::__Cr::allocator<base::sequence_manager::Task> >::DestroyContents (void)
00007ff7`54a5d4e0 chrome_exe!abort_noreturn (void)
...
...
```

### Steps to reproduce

1. run `x64dbg`
2. set `Option -> Preferences -> Misc -> Symbol Store`
   * https://chromium-browser-symsrv.commondatastorage.googleapis.com
3. attach to `chrome.exe` process
4. move to `Symbols` tab
5. click `chrome.exe` module
6. run `Download Symbols for This Module` in popup menu

**Comment by torusrxxx** [comment] 2024-10-31 02:01
duplicate of #3096

**Closed by torusrxxx** 2024-10-31 02:01 UTC
Labels: bug

**Comment by iamjimyes** [comment] 2024-10-31 02:49
This issue also occurs in WinDbg. It appears to be related to a problem with the symbol server at [chromium-browser-symsrv](https://chromium-browser-symsrv.commondatastorage.googleapis.com/)
