### ISSUE TITLE
plugins load error

### ISSUE THREAD

**Issue by bingzl** [x64dbg/x64dbg#430] opened 2015-11-18 05:35 UTC
你好，x64dbg的开发者
在x64dbg.com网站上所提供的插件，只有MultiASM是可以loadlibrary的，
其他所有插件都是不能加载。
我准备自己开发x64dbg的插件，请问插件SDK在网站中的什么位置？网站菜单中的插件URL是"http://x64dbg.com/#plugins"，我没有得到相关文档。
我的e mail： cracksec@gmail.com，希望得到沟通。
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Hello, x64dbg Coder
On the x64dbg.com site provided by the plugin, only MultiASM can be loadlibrary,
All other plugins are not loaded.
I am ready to develop their own x64dbg plug-in, which is the site of the plug-in SDK in what position? The plugin URL is "http://x64dbg.com/#plugins", I don't get the relevant documentation.

My mail: cracksec@gmail.com , I hope to get communication.

**Comment by bughoho** [comment] 2015-11-18 11:22
因为x64dbg是使用QT开发的，没有特别为中文系统做支持，所以注意不能放在含有中文字符的路径中。
至于SDK，把源码clone下来编译一遍，批处理文件中会把SDK（.h and .lib）复制到pluginsdk目录。

**Comment by mrexodia** [comment] 2015-11-18 17:43
@bughoho you are incorrect, there is support for Chinese path names (you can place x64dbg in a Chinese path name and debug files in a Chinese path name).

@bingzl Could you provide more information about which build you are using. There is no support for old build, get the latest build at http://releases.x64dbg.com

**Comment by bughoho** [comment] 2015-11-19 02:00
@mrexodia Thanks for reminding.indeed,I tested it again,there's no problem with the new version.

**Comment by bingzl** [comment] 2015-11-19 02:15
@mrexodia QT for the Chinese can not support, I am the fix version of  is low, can you fix this bug for Subsequent versions

**Comment by mrexodia** [comment] 2015-11-19 22:20
@bingzl Qt works fine with Chinese, what is the problem exactly?

@bughoho Please close this issue if all problems were solved for you.

**Comment by bingzl** [comment] 2015-11-20 01:39
@mrexodia I We find the problem is QtCore4.dll,X64dbg is not a problem.

**Comment by mrexodia** [comment] 2015-11-20 01:42
@bingzl I understand, but could you elaborate on what exactly the problem is? I don't speak Chinese and I can only test limited things (like unicode paths). I would like x64dbg to work for Chinese users as well.

**Comment by bingzl** [comment] 2015-11-20 02:59
@mrexodia QT specific issues I did not analyze in detail, 
I made a patch for QtCore4.dll. 
X64dbg can be independent of the Language file, easy to debug to modify.
If there is a need I can try to analyze bug

**Closed** 2015-11-21 03:18 UTC

**Comment by B1nGzl** [comment] 2015-11-21 13:29
@mrexodia I found the problem, QString encoding is Unicode, resource dialog encoding is Utf8 , so the garbled.
There are two fix methods：
1.Separate language file.
2.Program dialog encoding is utf8，and All of the.Cpp strings are replaced with.FromWCharArray () QString (L "TestString").
Two fixes can be resolved this bug

**Comment by bingzl** [comment] 2015-11-21 13:32
@mrexodia  I found the problem, QString encoding is Unicode, resource dialog encoding is Utf8 , so the garbled.
There are two fix methods：
1.Separate language file.
2.Program dialog encoding is utf8，and All of the.Cpp strings are replaced with.FromWCharArray () QString (L "TestString").
Two fixes can be resolved this bug

**Comment by xxxxnnxxxx** [comment] 2016-04-15 03:46
replace the pluginsdk as the latest, compiler the testplugin in vs2015,but it can't find the "List" type in 
"List<Module::ModuleInfo> modList;" how can i modify the error???
try the std:list ,it's wrong also
