### ISSUE TITLE
Memory Map Address Row Bugg

### ISSUE THREAD

**Issue by hxm-cpp** [x64dbg/x64dbg#2978] opened 2022-11-21 15:42 UTC
### Operating System

Windows 22H2 22621

### x64dbg Version

Oct 28 2022

### Describe the issue

![x64dbg_WCNzPxT3hx](https://user-images.githubusercontent.com/116516702/203095899-31cfe14b-5884-4571-9d57-300f9339d5c6.png)

### Steps to reproduce

![x64dbg_Tn3zjjVIiy](https://user-images.githubusercontent.com/116516702/203096740-cbe836cc-dce3-4fc5-af8b-812410d099ea.gif)

**Comment by foralost** [comment] 2023-02-26 11:18
So the problem is that all of the rows of the column 'Address' are being selected, when switching sections (.rdata -> .text)?
Does it occur everytime on any specified .exe?

Operating system is I assume Windows 11 22H2.

**Comment by mrexodia** [comment] 2023-02-26 12:13
This issue was already fixed, just forgot to close it…

**Closed by mrexodia** 2023-02-26 12:13 UTC
Labels: bug
