### ISSUE TITLE
Some wishes (FPU and other)

### ISSUE THREAD

**Issue by jin-x** [x64dbg/x64dbg#1624] opened 2017-06-16 17:53 UTC
Version Jun 8 2017
Win 7 x64 Ult SP1

I want to offer some new features and improvements...

1. Enter float numbers for ST(x) registers (right click -> change value)... now it's supported only hex - it's very strange! :((
2. Option to group long numbers by 4 or 8 digits: 0000`1111`2222`3333. And allow to enter numbers with division chars ' ` _ or spaces. Everywhere: in disasm code, register window, etc.
3. Option to show 0x20 bytes (instead of 0x10) in a row on dump window. Now this window is empty for a half (in 1920x1080).
4. Switching an order of FPU/SIMD registers (e.g. x87/MMX/XMM/YMM, MMX/XMM/YMM/x87, XMM/YMM/x87/MMX, YMM/XMM/MMX/x87) **or** disable visibility of SOME (show all/hide all FP/hide x87/hide x87 and MMX) **or** "_move up_" context menu item to move this register group (x87, MMX, XMM, YMM) to top (after POH and flags).
E.g. I want to see POH and XMM or YMM together (if I don't use FPU now). Now I need to list down and then up...
5. Sort of FPU registers by ST(x) instead of x87rX (like in OllyDbg). FPU instructions operates with ST(x) as a rule but not with x87rX. It's not easy to debug FPU programs with current sort :(
6. Allow to use a dot (.) when enter float numbers.

Thanks!

**Comment by mrexodia** [comment] 2017-06-21 13:53
I opened #1628 to address 1, 5 and 6

I opened #1629 to address 3

2 is a duplicate of #1565

4 is a duplicate of #888

**Comment by mrexodia** [comment] 2017-06-21 13:53
Next time, check for duplicate issues and open separate issues for unrelated requests please.

**Closed by mrexodia** 2017-06-21 13:53 UTC
