### ISSUE TITLE
Unresponsiveness to input when break on "DLL Load" is selected

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#516] opened 2016-01-27 08:29 UTC
- Applies to x32 only.

Steps:
1. Open x32dbg -> Options -> Preferences -> in the events tab, select `DLL Load`
2. Press `F3` and load any application
3. Press `F9`
4. When the debugger pauses (when the first module is loaded), press stop or restart.
5. Your next input won't do anything.

- At step (4), if you pressed `F9`, this issue won't be triggered,
although if you pressed `F9` 2 or 3 times and then pressed restart/stop, it will be triggered.
- Pressing the close button at the upper right would result in a funky/unusual behavior.
- Depending on whether you're lucky or not, the debugger may close/crash, or it may
just hang and can only be closed from taskmanager.
(if you're completely out of luck this day, even closing it from taskman won't be an option!
and you'll get an `Access denied` error msg)
- When you're in the middle of a debugging session (an app is already completely loaded and running ), this issue is completely false.

**Comment by Nukem9** [comment] 2016-01-27 22:36
Can't reproduce on windows 8. What OS version are you running?

**Comment by wk-952** [comment] 2016-01-27 23:48
Windows 8.1 Enterprise v6.3.9600 (64-bit), without any updates.

I've downloaded `snapshot_2016-01-25_01-04.7z` again just now and extracted it in a different
location than the usual one i use, so it's a clean build without any plugins, custom settings or anything,
and i can confirm to you this issue occurs.

**Comment by wk-952** [comment] 2016-02-17 22:00
Info thrown after crash:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	x32dbg.exe
  Application Version:	0.0.2.5
  Application Timestamp:	56c39a02
  Fault Module Name:	capstone.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	56b0e11f
  Exception Code:	c0000005
  Exception Offset:	000a2c5b
  OS Version:	6.3.9600.2.0.0.256.4
```
sometimes the faulty module is ntdll.
Dump files:
http://rghost.net/private/6Vpm25T4n/737e6e512cef5ceb38524df7ccf34616

Reproduced with latest snapshot.

**Comment by wk-952** [comment] 2016-06-01 21:58
Can't reproduce this anymore.

**Comment by wk-952** [comment] 2016-06-13 19:24
I managed to trigger this issue again today, but no as described in the first post.
dump file:
http://rgho.st/private/6gzyLcGrp/54373c183e97833ab4648235d0171328

password: `asd123`

**Comment by mrexodia** [comment] 2016-06-13 19:26
might be related to this annoying kernel deadlock in `NtReadVirtualMemory` in #580 @Nukem9 

![s](http://i.imgur.com/4oV59vi.png)

**Comment by mrexodia** [comment] 2016-06-13 19:35
Scrap that, probably unrelated.

**Comment by mrexodia** [comment] 2016-06-13 19:46
Okay it probably was fixed in commit 78908563 (didn't reproduce your exact issue though).

**Comment by wk-952** [comment] 2016-06-13 20:55
Not yet actually, here's another way using the latest snapshot
- Use a clean installation of the debugger, so everything is set to the default

1. Debug x96dbg.exe
2. You should land on the system breakpoint (log says `System breakpoint reached!`)
![1](https://cloud.githubusercontent.com/assets/11916365/16022720/91ec28e0-31b9-11e6-83dc-479d7669211c.png)

3. Select Options -> Preferences -> then select `DLL Load`
4. Press `F9` or `Shift + F9`, and you should land on a `RET` instruction,
(log says `DLL Loaded: XXXXXXXX C:\Windows\SysWOW64\imm32.dll`).
![2](https://cloud.githubusercontent.com/assets/11916365/16022739/b2002a0a-31b9-11e6-9f6b-f58d282cd46a.png)

5. Press stop

At this point the debugee won't stop, nor any input will be accepted, and you can only close it

**Comment by mrexodia** [comment] 2016-06-13 21:01
What I get: https://mega.nz/#!D15GgIYT!-ZhnszUwVjNQiAVS9m0eJiDVUewHRY1eoDSyIgAyltg

**Comment by wk-952** [comment] 2016-06-13 22:49
This is insane, turns out the problem was some kind of conflict with `Kaspersky`,
if `Kaspersky` is not loaded during account login (the protection is paused during OS boot-up), then everything is fine.
But if it's protection is resumed later on, then this issue occurs.
If it was again paused (or completely terminated), it won't matter, the issue will still be persistent.

@mrexodia I guess this issue is somehow "_offtopic_" since it's not the debugger's fault, feel free to close here if you want.

**Comment by wk-952** [comment] 2016-06-13 22:52
Note for self.
Maybe the original issue is not reproduce-able because of the OS change,
try win8.1 again.

**Closed** 2016-09-07 16:55 UTC
Labels: bug

**Comment by mrexodia** [comment] 2016-09-07 17:06
I tweeted at Kaspersky [here](https://twitter.com/x64dbg/status/773567813713797127) maybe we will get an answer.

**Comment by blaquee** [comment] 2016-09-07 17:07
Could you provide details of the Kaspersky version/product thats installed? and what feature exactly needs to be on to reproduce?

**Comment by wk-952** [comment] 2016-09-07 18:56
#### Tested on the following OS-es:
- Windows 8 Enterprise x64
- Windows 8.1 Enterprise x64
- Windows 10 Enterprise LTSB x64 (without Anniversary Update)
- Windows 10 Enterprise LTSB x64 (with Anniversary Update)

#### Tested on the following Kaspersky products:
- `Kaspersky Internet Security` (many versions, can't of course remember which, but it doesn't matter since this issue has been forever!)
- `Kaspersky Total Security v17.0.0.611(a)`
- Kaspersky modules/settings that needs to be turned on:
- I have no idea!, but i guess the default Kaspersky setup will do the job!. I'll setup a VM later and see if disabling/enabling certain components will make a difference and edit this post correspondingly.

#### Exact steps to reproduce this issue:
 - The issue seems to be only valid for `x32dbg.exe` (32-bit version of the debugger).
 - Make sure Kaspersky is running.
 - Use a clean installation of the debugger.

1. Open `x32dbg.exe` (no need to run as admin) then from the upper menu bar select `Tools` ---> `Preferences`
2. In the `Events` tab  select `DLL Load` and hit `Save`
![2](https://cloud.githubusercontent.com/assets/11916365/18324445/d0c7c4c2-753c-11e6-907b-cf665754d547.png)
3. Select `File` ---> `Open` (or just hit `F3`) and locate `x96dbg.exe` (should be in the root directory of the debugger)
4. You should land on the system function `ntdll.RtlUserThreadStart` (the log should say `"DLL Loaded: xxxxxxxx C:\Windows\SysWOW64\ntdll.dll"`)
![1](https://cloud.githubusercontent.com/assets/11916365/18324429/bfa5bf32-753c-11e6-8500-eaac9d6c0398.png)
5. Press `F9` once to run the debugger (the log should say `"DLL Loaded: xxxxxxxx C:\Windows\SysWOW64\kernel32.dll"`)
6. Try pressing `Stop` or `Restart`
7. The debugger will just do nothing!

#### How to workaround this issue:
A. Disable Kaspersky's auto startup from the settings
![k5](https://cloud.githubusercontent.com/assets/11916365/18324495/21708c9c-753d-11e6-9ef5-58483b175a2e.png)
B. Restart the computer
C. Again repeat steps from 1 - 6
D. The debugger will Stop/Restart normally
