### ISSUE TITLE
"Breakpoint on access" is not tracked correctly

### ISSUE THREAD

**Issue by dbsxdbsx** [x64dbg/x64dbg#2666] opened 2021-06-03 08:03 UTC
- Debugger version (can be found on right hand side of menu bar of debugger): 
May 8 2021
- Operating system version and Service Pack (including 32 or 64 bits): 
win10_64
- Brief description of the issue:
When looking for the base address of a data, I found that setting breakpoint on "access to a certain address" results in an incorrect result.

- Elaborate reproduction steps for the bug/issue being reported:
Install Cheat Engine 7.2;
launch the tutorial game from `help` menu;
In CE, try to find the value related to the game property called `Health`, 
Add the target value to the CE list, then right clicke the added value item and click `find out what accessed to this address`;
We would see something like this:
```
EAX=0180DF28
EBX=0180DF28
ECX=01847780
EDX=01847780
ESI=80006011
EDI=00000000
EBP=0165FCA8
ESP=0165FC9C
EIP=00425A4D

Probable base pointer =0180DF28

Label1
00425A41 - mov ebx,eax
00425A43 - cmp [ebx+000004AC],000003E8
00425A4D - jne 00425A7C
00425A4F - mov eax,[ebx+00000494]
```
Here `00425A43 - cmp [ebx+000004AC],000003E8` is the correct code, as `[ebx+000004AC]` equals the address storing the `Health`.

BUT, the same tracking thing can not be done in x64dbg (while it is feasible in Ollydbg):
In x64dbg：
1. attach the CE tutorial game;
2. ctrl+g, input the address storing `Health`;
3. then right click on the address in dump window;
4. select `breakpoint`-->'Memory, Access'-->`Single Shot`;
5. Program is paused but stopped at a wrong place:
```
00515EB2 | E8 19BEEEFF              | call <JMP.&MsgWaitForMultipleObjects>   |
00515EB7 | 8945 F8                  | mov dword ptr ss:[ebp-8],eax            |
00515EBA | 8B45 FC                  | mov eax,dword ptr ss:[ebp-4]            |
00515EBD | 8B80 74010000            | mov eax,dword ptr ds:[eax+174]          |   ------------->stopped  here
00515EC3 | 3B45 F8                  | cmp eax,dword ptr ss:[ebp-8]            |
00515EC6 | 76 10                    | jbe tutorial-i386.515ED8                |


EAX : 01867260
EBX : 0025D000
ECX : 5DE5F2C2
EDX : 00000000
EBP : 0165FEA8
ESP : 0165FE98
ESI : 00402B70     <tutorial-i386.EntryPoint>
EDI : 00402B70     <tutorial-i386.EntryPoint>
EIP : 00515EBD     tutorial-i386.00515EBD
EFLAGS : 00010246
......

```

After calculating, I found that `[eax+174] ` is not the correct address.

**Comment by mrexodia** [comment] 2021-06-03 09:35
Memory breakpoints are 0x1000 bytes long, if you use hardware breakpoints
like CE it should work.

**Comment by dbsxdbsx** [comment] 2021-06-03 09:41
@mrexodia, thanks for your advice. Indeed, it is working with hardware breakpoint. Besides, do you mean that even I just select 1 byte data in dump window  to set memory breakpoint, it would still set a breakpoint for totally 0x1000 bytes long?  Why would it be like that?

**Comment by mrexodia** [comment] 2021-06-03 09:51
It’s because it’s not implemented properly, it just changed the page
protection to add guard and then breaks whenever something accesses that
page.

**Comment by dbsxdbsx** [comment] 2021-06-03 10:00
@mrexodia ,Oh~ so it is a bug. Hopefully, it could be solved soon.

**Comment by mrexodia** [comment] 2021-06-03 10:14
If you put in the time I’m sure it can be solved soon. I don’t have time
unfortunately.

**Comment by dbsxdbsx** [comment] 2021-06-04 01:11
@mrexodia，which file(s) related to this feature should I dig into?

**Comment by mrexodia** [comment] 2021-06-04 16:24
The code path for setting memory breakpoints starts here: https://github.com/x64dbg/x64dbg/blob/18b949ee51a634bf5fff3ee717a765ba136cb791/src/dbg/commands/cmd-breakpoint-control.cpp#L688

Depending on how you would like to implement it you can either implement it in [TitanEngine](https://github.com/x64dbg/TitanEngine/blob/8d93135f382acd9317dc37d248c4499b091ac419/TitanEngine/TitanEngine.Breakpoints.cpp#L441)/[GleeBug](https://github.com/x64dbg/GleeBug/blob/vs2015/GleeBug/Debugger.Process.Breakpoint.cpp#L269). If I remember correctly the GleeBug implementation already supports smaller-sized memory breakpoints so it might be enough to modify how memory breakpoints are stored in x64dbg and add support for it.

**Comment by mrexodia** [comment] 2023-07-13 09:12
Duplicate of https://github.com/x64dbg/x64dbg/issues/1513

**Closed by mrexodia** 2023-07-13 09:12 UTC
Labels: enhancement
