### ISSUE TITLE
Known Structure representation

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#253] opened 2015-04-12 19:41 UTC
similar to the one in odbg 2.x would be a great feature...

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/253
- Originally reported by: Anonymous
- Originally created at: 2015-02-12T14:51:19.280

**Comment by azlan** [comment] 2015-12-31 05:20
![image](https://cloud.githubusercontent.com/assets/818761/12061436/2665dcc6-afc1-11e5-9e3d-5c7279f91bd0.png)

**Comment by mrexodia** [comment] 2016-09-07 07:18
duplicate of #225

**Closed by mrexodia** 2016-09-07 07:18 UTC
Labels: feature
