### ISSUE TITLE
Colourize dumps

### ISSUE THREAD

**Issue by jvoisin** [x64dbg/x64dbg#813] opened 2016-07-02 15:58 UTC
It would be great to colourize a bit the dump depending of the last operation on bytes, like read/write/execute.

**Comment by mrexodia** [comment] 2016-07-04 21:05
related/duplicate of #175 ?

**Comment by jvoisin** [comment] 2016-07-04 21:14
Likely related, since here it's about last read/written/executed. Feel free to close this and to edit #175 to make it a meta issue.

**Comment by LachJones** [comment] 2019-01-15 00:06
This seems to be implemented in current versions.

However there doesn't seem to be any documentation of which operation relates to which color, or when the colours are triggered. Is anyone able to help with this?

**Comment by torusrxxx** [comment] 2023-05-02 07:37
It isn't clear how to move forward on this

**Closed by torusrxxx** 2023-05-02 07:37 UTC
Labels: feature, gui
