### ISSUE TITLE
Memory BP

### ISSUE THREAD

**Issue by shargon** [x64dbg/x64dbg#382] opened 2015-08-27 17:16 UTC
Memory breakpoints works? for me dosen't work... in olly BPM stop but in x64bg, doing the same (memory access->single shot) dosen't stop

**Comment by mrexodia** [comment] 2017-12-11 02:07
closed in favor of #1513 because that one has a better description and actual reproduction steps.

**Closed by mrexodia** 2017-12-11 02:07 UTC
Labels: bug, not reproduced
