### ISSUE TITLE
ImportFuncError

### ISSUE THREAD

**Issue by nihuai** [x64dbg/x64dbg#1639] opened 2017-07-06 02:17 UTC
bug:
debugging program :VB
x64dbg and OD contrast
![vb-importfunc](https://user-images.githubusercontent.com/22935890/27892231-072e54ae-6231-11e7-8523-62f8e730f5c2.png)
[Example.zip](https://github.com/x64dbg/x64dbg/files/1126543/Example.zip)

Incidentally:
1.Unable to search multiple assembly instruction?
Only one search!
![only one search](https://user-images.githubusercontent.com/22935890/27892746-06d6ecf2-6234-11e7-8426-75068546cc6b.png)

2.Unable to process， without the pop-up to collapse window？
OD can pop up  window!
x64dbg Without this tip!
![od](https://user-images.githubusercontent.com/22935890/27892990-596dba80-6235-11e7-8ff4-95cee86e56b5.png)
![x64dbg](https://user-images.githubusercontent.com/22935890/27892993-5ca3d6da-6235-11e7-8b1a-89dc961203cc.png)

3.Can't analysis function parameters？
![func analysis](https://user-images.githubusercontent.com/22935890/27893181-ce9c6c42-6236-11e7-9a54-e4a120bb3c8f.png)

**Comment by mrfearless** [comment] 2017-07-06 10:22
Click on the msvbvm60.dll in the left column to show symbols for that dll
You can use this plugin: https://github.com/ThunderCls/xAnalyzer to show function parameters

**Comment by nihuai** [comment] 2017-07-07 02:41
@mrfearless Obvious errors，I said exe import function, PE tools to view the results, the number 69，x32dbg
![default](https://user-images.githubusercontent.com/22935890/27940932-6204aeee-6300-11e7-8aca-b3e90851f051.PNG)

**Comment by mrexodia** [comment] 2017-07-08 20:30
Duplicate of #569 and #297 

For the exception dialog, on last chance exception, use the command `con`

**Closed by mrexodia** 2017-07-08 20:30 UTC
