### ISSUE TITLE
Wrong parsing in dynamic comments

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#1227] opened 2016-11-07 15:41 UTC
The following expression won't work:
`{4:[esp] + 48}`
but if a space is added at the beginning it'll work
`{ 4:[esp] + 48}`
also it'll work if you eliminated the number of bytes to read
`{[esp] + 48}`

I guess the precedence of the this form `n:[addr]` should have higher priority, because this works
`{(4:[esp]) + 1}`
(manually forcing the precedence of calculation using brackets)

**Comment by mrexodia** [comment] 2016-11-07 15:59
try `{p:4:[esp]+48}` the issue is that '4' is recognized as a print type should be easy enough to fix

**Comment by mrexodia** [comment] 2016-11-07 18:32
Should be fixed, thanks!

**Closed by mrexodia** 2016-11-07 18:32 UTC
Labels: bug, easy

**Comment by wk-952** [comment] 2016-11-09 09:24
Alright, thanks.
I haven't been getting all notifications lately.

**Comment by mrexodia** [comment] 2016-11-09 09:26
Contact github about that there were issues with notifications they might
be able to assist.

**Comment by wk-952** [comment] 2016-11-09 09:36
Yeah this is getting really annoying to me, i'll contact them today.
