### ISSUE TITLE
 instruction “cmp” small error

### ISSUE THREAD

**Issue by stonedreamforest** [x64dbg/x64dbg#1477] opened 2017-02-22 07:18 UTC
x64 
![default](https://cloud.githubusercontent.com/assets/16742566/23200816/6b483060-f911-11e6-8c62-eb1f16e6ba1f.png)

cmp **dword ptr** ds:[r8+20],FFFFFFFFFFFFFFFF
->
cmp **dword ptr** ds:[r8+20],FFFFFFFF

**Comment by mrexodia** [comment] 2017-02-22 19:14
duplicate of #1448

**Closed by mrexodia** 2017-02-22 19:14 UTC
