### ISSUE TITLE
Debugger crash when symbols are present

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#323] opened 2015-06-21 06:06 UTC
To reproduce this:
*) Make sure you have all symbols downloaded first (i'm not sure which one causes this issue).
1- Load any application in the debugger
2- Restart the application being debugged 18 times
3- On restart attempt number 19, the debugger will crash

* Information thrown after crash:

--------------------------------------------------------------

Problem signature:
  Problem Event Name:	BEX
  Application Name:	x32dbg.exe
  Application Version:	0.0.2.5
  Application Timestamp:	558646fd
  Fault Module Name:	MSVCR120.dll
  Fault Module Version:	12.0.21005.1
  Fault Module Timestamp:	524f7ce6
  Exception Offset:	000a7666
  Exception Code:	c0000409
  Exception Data:	00000007
  OS Version:	6.3.9600.2.0.0.256.4

--------------------------------------------------------------

- This issue is introduced since commit da6b666 ,
   building the project with any previous commit seems fine.
- When pressing "Debug this application" (while x64dbg is set as the JIT debugger),
  x64dbg is loaded up to debug itself but it immediately says "debugging stopped!".
- It doesn't happen when the symbols folder is not present.
- If ScyllaHide plugin is installed, the plugin issue from here #303 (plugin file couldn't be loaded)
  will occur at restart number 18.
- Latest snapshot at sourceforge (snapshot_2015-06-20_02-39) also has this issue.
- This issue was reproduced after building the project with the latest commit 9cc5949 .

**Comment by wk-952** [comment] 2015-06-21 18:58
Call Stack table, got it by luck:
http://rghost.net/private/6QVHCSk9P/d0c15be5fba914ac4679cd578ed5e3f4


Here is also a screenshot of the disassembly window from the JIT debugger x64dbg:
![err](https://cloud.githubusercontent.com/assets/11916365/8272909/885841f6-1856-11e5-9eee-d59c44873b52.jpg)

**Comment by mrexodia** [comment] 2015-06-21 19:06
Amazing! I also encountered this crash. It might be the memory map. Didn't
expect that.

**Comment by wk-952** [comment] 2015-06-22 06:23
still the same :(

**Comment by wk-952** [comment] 2015-06-22 07:04
ok, i found an easy way to debug x64dbg (why didn't i think of this earlier!)
i opened x64dbg and loaded up a game with it (let's call it game debugger),
then i opened another instance of x64dbg and attached the game debugger (JIT debugger).

After that everything was easy, at restart 18 exactly the game debugger broke and the JIT debugger
reported an access violation error, now it was easy to copy the call stack table, so here it is:
http://rghost.net/private/7GdmZDrYT/bdb2ccc530fa9237922c6744fb210dc5

and also a screenshot of the disassembly window from the JIT debugger at crash:
![222_err](https://cloud.githubusercontent.com/assets/11916365/8276990/aec25806-18bd-11e5-8823-b697bb766d44.png)

**Comment by onesbug** [comment] 2015-06-22 10:20
I found a similar problem.If you press the restart button quickly,All the buttons are invalid.

**Comment by mrexodia** [comment] 2015-07-13 05:16
I think is issue is resolved now.

**Comment by wk-952** [comment] 2015-07-13 19:23
It now happens at restart number 74,
also now it doesn't only crash, but also the debugging data gets lost,
and as mentioned in the first post, the files of ScyllaHide plugin could not be loaded,
so the same effects as in issue #303.

For your convenience i removed the symbols folder and tried again, and i was able to restart the application 84 times with no problems,
then i restored the symbols folder and manually compiled the project after adding line # 726 from this commit da6b666 , and this time i reached restart # 100 with no errors or crashes while the symbols are present.

**Comment by mrexodia** [comment] 2015-07-14 00:28
Hey,

Today I restarted about 200 times. Couldn't reproduce it unfortunately... Does it crash at the same number of restarts for you every time? And is the callstack still the same? Nukem added a crashdump thing in one of the latest commits. Could you try to reproduce do we get a crashdump?

I also fixed various crashes, so it might be solved.

**Comment by wk-952** [comment] 2015-07-14 01:51
not exactly, but it's around this range [73, 76] so for me it's not hard to reproduce,
i'll re-compile the project again with those latest 8 commits (the ones done about 3 hours ago)
then if it happened again i'll upload the callstack and the information thrown after crash if it's different.

About the new crashdump feature, could you please tell me how should i do it ? so i can upload it as well with the callstack

**Comment by mrexodia** [comment] 2015-07-14 01:53
Just get the latest master. The crashdumps are created in a folder called
'minidump'. Just upload anything you get in there.

**Comment by wk-952** [comment] 2015-07-14 03:54
Okay, here is what happened in the past 2 hours:
* First it's worth mentioning that now after crashing, no debugging data is lost.

-Attempt 1:
After 73 -74 restarts i got the error: "MiniDumpWriteDump failed. Error: 2147942408"
had to press ok about 6 times or more for that error.
When the debugger crashed it didn't give me the chance to debug it (no "Debug this application" option), but the minidump folder wasn't empty! so i included that in the archive.

-Attempt 2:
Exactly as attempt 1, but this time after crash i had the option to debug the application (x64),
and wonder what happened when i pressed "Debug this application" ....
as mentioned in the first post: " x64dbg is loaded up to debug itself but it immediately says 'debugging stopped!' ", and again the minidump folder had some files in it (although "MiniDumpWriteDump" error occurred again).

-Attempt 3:
This is the interesting one, i did what i mentioned in the 5th post to be able to catch the error when it happens so i can dump the callstack since this was the only way i could do it.
There was a problem here first:
1- open the JIT debugger and the game debugger.
2- attach the game debugger to the JIT debugger.
3- load any game/app in the game debugger.
4- you immediately get a dumping error: "Failed to open file path 'xxx' while generating crash dump" (where 'xxx' is the full path to the dump file).
I guess because the JIT and the game debuggers (who's in fact x64dbg opened twice from the same location) are trying to access the same dump file, so i copied x64dbg (game dbg) to another location, this time when i reproduced the issue and the error occurred, the JIT dbg broke/paused and i could copy the stackcall table.

- Between each attempt i removed the minidump folder to make sure it's a clean try with its own dumps.
- In the last attempt the JIT dbg didn't give the "MiniDumpWriteDump" error, but the game dbg did.
- OS: Windows 8.1 Enterprise 64-bit.

http://rghost.net/private/7pTnsthrC/e2d97320247ea6b5de1bfb702f987cdd
password: asd123

**Comment by Nukem9** [comment] 2015-07-14 04:17
Thanks for the info!

1.
`2147942408` translates to `0x80070008` - `not enough storage is available to process this command.` I don't know the exact reason for this right now.

2.
One question (if you have time): if you open `crashdump.cpp` and go to [this line](https://github.com/x64dbg/x64dbg/blob/master/x64_dbg_exe/crashdump.cpp#L96) in your _own_ repository, do they match? Based on the generated .dmp files it should be impossible for them to even exist.

**Comment by wk-952** [comment] 2015-07-14 04:27
Ii don't clone to my repository, i always download the master branch as a zip file
here's what i see in the crashdump.cpp.
I'll upload later today all the symbols i have along with the build i recompiled.
![untitled2](https://cloud.githubusercontent.com/assets/11916365/8666406/1bbb4dfc-29f1-11e5-81d9-e2a76a1238da.jpg)

**Comment by Nukem9** [comment] 2015-07-14 04:28
Yeah that was what I worried about. `!=` should be `==` .....this is fixed in the newest commits.

**Comment by wk-952** [comment] 2015-07-14 04:30
oh crap!, ok no problem i'll do attempt 3 again (very sorry)

**Comment by wk-952** [comment] 2015-07-14 05:10
It's even worse, i didn't find any dump files in the JIT dbg, and the dump files in the game dbg were 0 byte files!, but anyway here is the callstack again with pics at crash time and at DumpWrite error:

http://rghost.net/private/86VmCdQgh/40091aa4c335b0a422f2bd4bd30159f1
password: asd123

Those are the symbols for x32 that i use:
http://rghost.net/private/6S8RRL4L4/3440b5807168148b13236099c8c7fba0

**Comment by Nukem9** [comment] 2015-07-14 05:14
Thanks. There's a Windows bug with the 0-byte dmp files I guess. Nothing I can do.

However, I managed to reproduce an exception myself (it takes around 500 restarts)
```
0:004> kb
ChildEBP RetAddr  Args to Child              
00d3bdd0 750f43a1 00000000 00000000 00000000 USER32!NtUserWaitMessage+0xc
00d3be18 750e4fcd 00000000 00000000 00000000 USER32!DialogBox2+0x13f
00d3be48 750ef907 00000000 750ee3f0 00d3c090 USER32!InternalDialogBox+0x107
00d3bf14 750ef06d 00d3c090 5517f630 00000000 USER32!SoftModalMessageBox+0xe2c
00d3c078 7513781b 5517f630 25649f20 00000000 USER32!MessageBoxWorker+0x293
00d3c0fc 7513777b 00000000 5517f630 25649f20 USER32!MessageBoxTimeoutW+0x6b
00d3c130 751375bb 00000000 00d3c184 011c2168 USER32!MessageBoxTimeoutA+0x7b
00d3c150 75137588 00000000 00d3c184 011c2168 USER32!MessageBoxExA+0x1b
00d3c16c 011c1207 00000000 00d3c184 011c2168 USER32!MessageBoxA+0x18
00d3c588 011c11a5 011c2254 8007001f 00000000 x32dbg!CrashDumpFatal+0x47 [e:\projects\x64_dbg\x64_dbg_exe\crashdump.cpp @ 40]
00d3c9d0 011c127a 00d3c9f8 00d3ca2c 77286846 x32dbg!CrashDumpCreate+0x185 [e:\projects\x64_dbg\x64_dbg_exe\crashdump.cpp @ 87]
00d3c9dc 77286846 00d3c9f8 00d3cb28 00d3cad8 x32dbg!CrashDumpVectoredHandler+0x1a [e:\projects\x64_dbg\x64_dbg_exe\crashdump.cpp @ 101]
00d3ca2c 772ed8e1 00000000 00d3d000 00000000 ntdll!RtlpCallVectoredHandlers+0xba
00d3cac0 772c09bf 00d3cad8 00d3cb28 00d3cad8 ntdll!RtlDispatchException+0x72
00d3cac0 74f9b61d 00d3cad8 00d3cb28 00d3cad8 ntdll!KiUserExceptionDispatcher+0xf
00d3cf94 53ab838f 00d3d000 00000000 00000002 msvcrt!memcpy+0x198
00d3cfb0 53ab7332 00000000 00000000 00000000 dbghelp!ReadImageData+0x4c
00d3d370 53ab6bc7 c3fd9543 7b5d4800 7b605bb8 dbghelp!ReadHeader+0x171
00d3d3a8 53ab5afe c3fd9ea3 750c0000 00000000 dbghelp!imgReadLoaded+0xad
00d3d848 53ab611c 76bd2170 00ae4740 00000000 dbghelp!modload+0x1a6
00d3dcbc 53aafb3a 00000000 750c0000 00000000 dbghelp!LoadModule+0x309
00d3dd18 507c22c8 00002964 00002afc 00ae4740 dbghelp!SymLoadModuleEx+0x45
00d3dd50 507c6510 00002964 00002afc 00d3e6d4 x32dbg_50790000!SafeSymLoadModuleEx+0x38 [e:\projects\x64_dbg\x64_dbg_dbg\dbghelp_safe.cpp @ 76]
00d3ede4 53c5e4c2 53cbb6dc 507c43e0 507c43e0 x32dbg_50790000!cbLoadDll+0x160 [e:\projects\x64_dbg\x64_dbg_dbg\debugger.cpp @ 839]
WARNING: Stack unwind information not available. Following frames may be wrong.
00d3fb58 507c48fb c0c5a406 00d3fc70 508c14a8 TitanEngine!DebugLoop+0x1ad2
00d3fc9c 76ba7c04 508c2558 76ba7be0 e682a121 x32dbg_50790000!threadDebugLoop+0x51b [e:\projects\x64_dbg\x64_dbg_dbg\debugger.cpp @ 1184]
00d3fcb0 772db54f 508c2558 e773911e 00000000 KERNEL32!BaseThreadInitThunk+0x24
00d3fcf8 772db51a ffffffff 772c0404 00000000 ntdll!__RtlUserThreadStart+0x2f
00d3fd08 00000000 507c43e0 508c2558 00000000 ntdll!_RtlUserThreadStart+0x1b
```

**Comment by Nukem9** [comment] 2015-07-14 06:45
I can't cause it to crash any longer. ba63ac30576c674ba6c3182fdec6fa3ce536e14f seems to have fixed it. Just waiting for your confirmation.

**Comment by wk-952** [comment] 2015-07-14 07:33
i'll try it now and edit this post correspondingly

**Closed** 2015-07-14 08:15 UTC

**Comment by mrexodia** [comment] 2015-07-14 08:28
amazings! hopefully the bugs stay away from now on :+1:
