### ISSUE TITLE
Wrong disassembly of 32-bit registers and immediate operands in 64-bit mode

### ISSUE THREAD

**Issue by lhmouse** [x64dbg/x64dbg#1448] opened 2017-02-02 14:36 UTC
On x64 the machine code `83 F9 FF` is decoded as `cmp ecx, FFFFFFFFFFFFFFFF` which compares a 32-bit register with a 64-bit immediate. In spite that the immediate is sign-extended, if an unsigned format is preferred the correct code should be `cmp ecx, FFFFFFFF`.

**Comment by lhmouse** [comment] 2017-02-03 07:43
How is this `not reproduced`??
You just pick an arbitrary x64 executable, open it with x96dbg, press `Ctrl+E` in the disassembly tab, enter `83 f9 ff` then Click OK.
![9411](https://cloud.githubusercontent.com/assets/5071344/22583420/6d29182a-ea27-11e6-8f3d-2c81f6ae65d6.png)

**Comment by mrexodia** [comment] 2017-02-03 07:44
@lhmouse the not reproduced label means that I have not reproduced the issue yet.

**Comment by lhmouse** [comment] 2017-02-03 07:46
Oh fair enough. The label is extremely misleading to me.

**Comment by lhmouse** [comment] 2017-02-03 07:56
Thanks.

One more word: I didn't receive any notification about the action that someone (you) had added some labels. Would you please add a comment after it, letting people (me) know they must provide more information?

**Comment by mrexodia** [comment] 2017-02-03 08:14
No, I did not require more information. The labels on issues are intended for developers, in general they are not relevant for the person reporting the issue.

**Comment by mrexodia** [comment] 2017-02-24 18:48
The issue should be fixed now:

```
00000000004014DB | 80 F9 FF    | cmp cl,FF
00000000004014DE | 66 83 F9 FF | cmp cx,FFFF
00000000004014E2 | 83 F9 FF    | cmp ecx,FFFFFFFF
00000000004014E5 | 48 83 F9 FF | cmp rcx,FFFFFFFFFFFFFFFF
```

**Closed** 2017-02-24 18:48 UTC
Labels: bug

**Comment by lhmouse** [comment] 2017-02-25 02:44
Thanks. :joy:
