### ISSUE TITLE
x32dbg instantly unloads .dll after loading

### ISSUE THREAD

**Issue by Zapeth** [x64dbg/x64dbg#1495] opened 2017-03-13 16:23 UTC
First off this happens only with a specific .dll, other randomly selelected .dlls loaded fine. However since the according .exe that uses this specific .dll works fine and it also loads in ollydbg, I don't think the problem lies with the .dll.

The .dll in question is the client.dll from the Half-Life mod Counter-Strike v1.3, for simplicities sake I uploaded just the .dll [here](https://filebin.net/dapfl5cmz19g71gw) but if you dont trust that link feel free to extract it from the original setup that you can download from [Moddb](http://www.moddb.com/mods/counter-strike/downloads/counter-strike-13).

And I was wondering if its normal that x32dbg leaves a DLLLoader32_xxxx.exe file in the .dll directory for every .dll that you try to load? Because it is kind of annoying having to clean it up every time, would be nice if that file could be kept entirely in memory or at least have it deleted after unloading/exiting.

Last but not least, I'm using the latest snapshot (2017-03-13_03-35) on Win7-64bit.

**Comment by Zapeth** [comment] 2017-03-13 16:35
Whoops nevermind, I forgot that the .dll is dependant on another .dll in the executed directory (which I copied into ollydbg's directory some time ago), after putting that dependant .dll in x32dbg's directory the problematic .dll loads fine.

However there was zero feedback from the log of what went wrong (which isn't the case in ollydbg iirc), so if its possible to check for a missing dependency when loading the .dll then I think that should be output in the log when that dependency isn't found.

**Comment by mrexodia** [comment] 2017-03-13 17:33
Duplicate of #45 

Also, you should never have to copy a dll to the x64dbg directory. The DLL loader should clean up automatically too but there is a bug somewhere with that.

**Closed by mrexodia** 2017-03-13 17:33 UTC
