### ISSUE TITLE
x64dbgpy Script error, missing parameter

### ISSUE THREAD

**Issue by nihuai** [x64dbg/x64dbg#1760] opened 2017-10-14 13:46 UTC
The function call fails.
The prompt requires a third parameter.
But python scripts have only two parameters.

![image](https://user-images.githubusercontent.com/22935890/31576156-fe8e0a6a-b127-11e7-8367-99e317ad53ea.png)
![image](https://user-images.githubusercontent.com/22935890/31576227-02e60be8-b129-11e7-9791-11a00e5148ba.png)

**Comment by mrexodia** [comment] 2017-10-14 13:48
Perhaps try to add another parameter and see if it works?

**Comment by nihuai** [comment] 2017-10-14 13:53
@mrexodia
It's painful to use without helping documents
Adding three parameters is also wrong

**Comment by mrexodia** [comment] 2017-10-14 13:54
try `_x64dbg.Find(data, len(data), pattern)`

I agree that without documentation it is hard but there was no time to write documentation for this branch. See the pybind11 branch for a design of the new API with documentation.

**Comment by nihuai** [comment] 2017-10-14 14:04
_x64dbg.Find() ,also not line

**Comment by mrexodia** [comment] 2017-10-14 15:36
Duplicate of https://github.com/x64dbg/x64dbgpy/issues/18

**Closed by mrexodia** 2017-10-14 15:36 UTC
