### ISSUE TITLE
BSOD after the step on popad and popfd

### ISSUE THREAD

**Issue by Deyvan** [x64dbg/x64dbg#2603] opened 2021-02-28 19:55 UTC
- x32dbg version: Feb 9 2021
- Windows 10 LTSC x64

After debug of popfd popad instructions, a BSOD occurs
And this happens under any circumstances

Sorry for the video quality.
https://www.youtube.com/watch?v=qr7gLcXVLlU

**Comment by Mattiwatti** [comment] 2021-03-01 21:56
Can you upload a kernel crash dump? I can't reproduce this here.

**Comment by daaximus** [comment] 2021-03-01 21:58
I'm curious what the state of the CPU was when executing these -- GPRs, EFLAGS, all other registers and what, if any, driver was associated with the bsod. If none, the state information would be useful as well as where you did this specifically to make it occur (whether it seems relevant or not.)

**Comment by Deyvan** [comment] 2021-03-02 16:50
Crash dump:
[022821-64531-01.zip](https://github.com/x64dbg/x64dbg/files/6070305/022821-64531-01.zip)

**Comment by Deyvan** [comment] 2021-03-02 16:59
> 
> 
> I'm curious what the state of the CPU was when executing these -- GPRs, EFLAGS, all other registers and what, if any, driver was associated with the bsod. If none, the state information would be useful as well as where you did this specifically to make it occur (whether it seems relevant or not.)

The error may also appear after normal use of popad popfd, i.e.
77CECFDC | 9C | pushfd |
77CECFDD | 60 | pushad |
77CECFDE | 61 | popad |
77CECFDF | 9D | popfd |

I have no idea why this is happening

**Comment by daaximus** [comment] 2021-03-03 05:00
We've been trying to replicate the issue and have been unable to do so. Are there specific things you're doing leading up to this? Are you doing it with any certain plugins running for x64dbg? TitanHide? It seems that it failed because of stack cookie corruption -- but that doesn't make much sense with just using x64dbg by itself.

Arg1: ffffa08a62f46d00, Actual security check cookie from the stack
Arg2: 000050f971ea3deb, Expected security check cookie
Arg3: ffffaf068e15c214, Complement of the expected security check cookie
Arg4: 0000000000000000, zero

**Comment by Nukem9** [comment] 2021-03-03 12:08
I skipped the stack cookie failure and looked at the cause of the second page fault and it doesn't make any sense. Am I missing something?

```
3: kd> kv
 # Child-SP          RetAddr           : Args to Child                                                           : Call Site
00 ffffa08a`62f45a88 fffff800`1811b2e5 : 00000000`000000f7 ffffa08a`62f46d00 000050f9`71ea3deb ffffaf06`8e15c214 : nt!KeBugCheckEx
01 ffffa08a`62f45a90 fffff800`1804dd3e : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000001 : nt!_report_gsfailure+0x25
02 ffffa08a`62f45ad0 fffff800`1804dcd3 : 00000000`00000050 fffff800`17ed6f62 00000000`00000000 00000000`00000001 : nt!_GSHandlerCheckCommon+0x5a
03 ffffa08a`62f45b00 fffff800`18076f72 : fffff800`18395000 fffff800`17eb7000 0005b668`00a6c000 00000000`0010001f : nt!_GSHandlerCheck+0x13
04 ffffa08a`62f45b30 fffff800`17ed6390 : ffffa08a`62f46180 00000000`00000000 ffffa08a`62f460a0 fffff800`182469b4 : nt!RtlpExecuteHandlerForException+0x12
05 ffffa08a`62f45b60 fffff800`17f789c4 : ffffa08a`62f46a98 ffffa08a`62f467e0 ffffa08a`62f46a98 00000000`00000000 : nt!RtlDispatchException+0x430
06 ffffa08a`62f462b0 fffff800`1807fdc2 : 00000000`00000000 ffffa08a`62f46b40 00000000`00001000 00000000`00000031 : nt!KiDispatchException+0x144
07 ffffa08a`62f46960 fffff800`1807c0ae : ffffb801`b6b53080 ffffa08a`62f46d70 00000000`00000002 fffff800`182ea9c0 : nt!KiExceptionDispatch+0xc2
08 ffffa08a`62f46b40 fffff800`17eec68a : ffffa08a`62f46d70 fffff800`186c3bf1 00000000`00000010 00000000`00000246 : nt!KiPageFault+0x42e (TrapFrame @ ffffa08a`62f46b40) <---- Looking at this frame
09 ffffa08a`62f46cd0 fffff800`186c3bf6 : fffff800`182ea9c0 ffffb801`00000001 00000000`00000000 ffffa08a`62f46fb0 : nt!ExReleaseFastMutex+0xa
0a ffffa08a`62f46d00 00000000`00000001 : 00000000`003bfda0 ffffa08a`62f47a58 ffffb801`c0782080 ffffb801`c0782080 : nt!DbgkpQueueMessage+0x212
0b ffffa08a`62f46f00 00000000`003bfda0 : ffffa08a`62f47a58 ffffb801`c0782080 ffffb801`c0782080 00000000`00000001 : 0x1
0c ffffa08a`62f46f08 ffffa08a`62f47a58 : ffffb801`c0782080 ffffb801`c0782080 00000000`00000001 fffff800`186c5238 : 0x3bfda0
0d ffffa08a`62f46f10 ffffb801`c0782080 : ffffb801`c0782080 00000000`00000001 fffff800`186c5238 00000000`00000000 : 0xffffa08a`62f47a58
0e ffffa08a`62f46f18 ffffb801`c0782080 : 00000000`00000001 fffff800`186c5238 00000000`00000000 00000000`00000000 : 0xffffb801`c0782080
0f ffffa08a`62f46f20 00000000`00000001 : fffff800`186c5238 00000000`00000000 00000000`00000000 00000000`00000000 : 0xffffb801`c0782080
10 ffffa08a`62f46f28 fffff800`186c5238 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x1
11 ffffa08a`62f46f30 fffff800`186503e4 : ffffb801`c5c61380 ffffa08a`62f47080 ffffb801`c0782080 00000000`00000000 : nt!DbgkpSendApiMessage+0xa4
12 ffffa08a`62f46f80 fffff800`17f78b3b : ffffa08a`62f47a58 ffffa08a`62f47a58 ffffa08a`62f47130 00000000`00ca173c : nt!DbgkForwardException+0xd7788
13 ffffa08a`62f47100 fffff800`1807fdc2 : 00000000`00000001 ffffa08a`62f47b00 00000000`00001000 00000000`00000000 : nt!KiDispatchException+0x2bb
14 ffffa08a`62f47920 fffff800`1807c0ae : ffffb801`b6b53080 00000000`00000000 00000000`00000000 ffffb801`c0745060 : nt!KiExceptionDispatch+0xc2
15 ffffa08a`62f47b00 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiPageFault+0x42e (TrapFrame @ ffffa08a`62f47b00) <---- Single step from a.exe+x64dbg, ignored

3: kd> .trap ffffa08a`62f46b40
NOTE: The trap frame does not contain all registers.
Some register values may be zeroed or incorrect.
rax=0000000000000000 rbx=0000000000000000 rcx=0000000000000001
rdx=0000000000000000 rsi=0000000000000000 rdi=0000000000000000
rip=fffff80017eec68a rsp=ffffa08a62f46cd0 rbp=0000000000000000
 r8=000000000004001f  r9=000000000000001f r10=0000fffff80017ff
r11=ffff797e4b400000 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei ng nz na pe nc

nt!ExReleaseFastMutex+0xa:
fffff800`17eec68a 0fb67930        movzx   edi,byte ptr [rcx+30h] ds:00000000`00000031=?? <---- How did this happen? How did RCX become 0x1?
```

Checking the partial disassembly of DbgkpQueueMessage calling ExReleaseFastMutex:
```
3: kd> uf nt!DbgkpQueueMessage+0x212
...
nt!DbgkpQueueMessage+0x206:
fffff800`186c3bea 488d0dcf6dc2ff  lea     rcx,[nt!DbgkpProcessDebugPortMutex (fffff800182ea9c0)] <---- RCX == 0xfffff800182ea9c0 after execution
fffff800`186c3bf1 e88a8a82ff      call    nt!ExReleaseFastMutex (fffff80017eec680)               <---- ExReleaseFastMutex(&DbgkpProcessDebugPortMutex);
fffff800`186c3bf6 85f6            test    esi,esi
fffff800`186c3bf8 0f8898000000    js      nt!DbgkpQueueMessage+0x2b2 (fffff800186c3c96)

...

3: kd> uf nt!ExReleaseFastMutex
fffff800`17eec680 48895c2408      mov     qword ptr [rsp+8],rbx
fffff800`17eec685 57              push    rdi
fffff800`17eec686 4883ec20        sub     rsp,20h
fffff800`17eec68a 0fb67930        movzx   edi,byte ptr [rcx+30h] <---- RCX never written or accessed up until this point
```

RCX is never modified after the LEA instruction in DbgkpQueueMessage. It should be 0xfffff800182ea9c0, which wouldn't cause a fault, but it turns into 0x1 at some point. Why?

**Comment by Deyvan** [comment] 2021-03-03 13:01
> 
> 
> We've been trying to replicate the issue and have been unable to do so. Are there specific things you're doing leading up to this? Are you doing it with any certain plugins running for x64dbg? TitanHide? It seems that it failed because of stack cookie corruption -- but that doesn't make much sense with just using x64dbg by itself.
> 
> I'm curious where you were overwriting this and what your sample application is doing (the `a.exe`).
> 
> Arg1: ffffa08a62f46d00, Actual security check cookie from the stack
> Arg2: 000050f971ea3deb, Expected security check cookie
> Arg3: ffffaf068e15c214, Complement of the expected security check cookie
> Arg4: 0000000000000000, zero

I repeated without plugins bsod still occurs 🤔
Function where i triggered bsod a.exe+5E87

[q.zip](https://github.com/x64dbg/x64dbg/files/6076094/q.zip)

**Comment by manxorist** [comment] 2021-12-20 06:46
I am not a x64dbg user, but I am seeing probably the same issue with the Visual Studio debugger. I have reported the issue to Microsoft at <https://developercommunity.visualstudio.com/t/BSOD-when-single-stepping-over-popfd-i/1617674>, but I doubt that I was able to provide enough information there.

@Deyvan can you provide your system details? Maybe we can correlate common system properties in order to narrow down how to reproduce the issue.

**Comment by Deyvan** [comment] 2021-12-21 18:00
No, It seems that the information about her was not necessary 😅

**Comment by Deyvan** [comment] 2024-05-27 10:04
After buying a new processor, the problem disappeared 💀

**Comment by mrexodia** [comment] 2024-05-27 11:44
Well, thanks for coming back to the issue after 3 years! My guess is that this is an issue with Hyper-V on older processors. I will close the issue, because it looks like x64dbg cannot do anything about it anyway...

**Closed by mrexodia** 2024-05-27 11:44 UTC
Labels: bug, try this
