### ISSUE TITLE
cannot assemble "call MessageBoxA" with keystone

### ISSUE THREAD

**Issue by torusrxxx** [x64dbg/x64dbg#891] opened 2016-07-27 10:09 UTC
and "call 0x MessageBoxA" shows a successful message but ends with error.

**Comment by mrexodia** [comment] 2016-07-27 10:12
Yeah see the issue of custom parser. Also report bugs in the keystone
repository that might solve the problem.

**Comment by mrexodia** [comment] 2016-11-05 19:08
closed as duplicate of #776

**Closed by mrexodia** 2016-11-05 19:08 UTC
Labels: bug
