### ISSUE TITLE
[Feature Request] Symbols Tab: Show Module name for Imported symbols

### ISSUE THREAD

**Issue by Dwedit** [x64dbg/x64dbg#2328] opened 2020-04-25 23:00 UTC
Version April 12, 2020
Windows Version: 10.0.18363.778

This is a feature request.
In OllyDbg, when you display the Imports and Exports of a module, you can see module names.  For example, Imports are named &KERNEL32.WriteFile or &KERNEL32.GetStdHandle.
Screenshot of OllyDbg: https://i.imgur.com/MPM15Bp.png

Meanwhile in X64Dbg, when you go to the Symbols Tab and select a module, then look at the Imports and Exports, module names are not included.  You only see the names WriteFile or GetStdHandle, without information about which module they belong to.
Screenshot of X64Dbg: https://i.imgur.com/bOiGJGg.png

It would be really nice if there was a column for Module Name available, or at least the names of the symbols had the DLL name attached to them.

Edit: Appears to be a duplicate of Issue #1804

**Comment by mrexodia** [comment] 2020-06-07 15:54
Duplicate of #1804

**Closed by mrexodia** 2020-06-07 15:54 UTC
