### ISSUE TITLE
attach registers to the dump tabs

### ISSUE THREAD

**Issue by lastfun** [x64dbg/x64dbg#610] opened 2016-03-16 21:54 UTC
Hi) a wonderful job!
if this possible - attach registers to the dump tabs.
Thx :)
For example:
![x64](https://cloud.githubusercontent.com/assets/17525023/13829931/b9c44688-ebda-11e5-852a-ca0ea9d4b56b.png)

**Comment by mrexodia** [comment] 2016-03-16 23:04
duplicate of #548

**Closed by mrexodia** 2016-03-16 23:04 UTC
