### ISSUE TITLE
check plugin update

### ISSUE THREAD

**Issue by tqangxl** [x64dbg/x64dbg#1896] opened 2018-02-10 00:33 UTC
auto or M check plugin update available

**Comment by mrfearless** [comment] 2018-02-10 00:55
requires a few things for that, either:

* Author of plugin makes an update function in their own plugin
or
* A standardized plugin update api with information supplied to plugin by plugin author:
  - full url to plugin version text file to compare version no with of plugin with plugin text file
  - full url to plugin's .dp32 / .dp64 file 

Other potential work required or issues to be addressed:
* For some plugins updating will require restart as opposed to the hot unload/load of them (depends on plugin)
* Some plugins may require additional files to be downloaded for them to work and be placed in specific folders (xAnalyzer for example would require the .api and .api.h files in the api_def folder) so a seperate zip or archive for downloading and logic to handle this plugin update might be necessary in some cases (depending on plugin).
* Plugin api has to take in account new plugin files (downloaded to a temp folder?) to copy into plugins folder
* Plugin api backup of older plugin files before replacing?
* Security of plugins: signed and/or verified by someone?, hostile takeover/redirect of original plugin location and replaced with file names as plugin that is malware/randomsware/cryptominer/etc

I think @mrexodia has a work in progress document related to this and future development of the plugin api in general

**Comment by mrexodia** [comment] 2018-02-10 20:40
Duplicate of #1679

**Closed by mrexodia** 2018-02-10 20:40 UTC
