### ISSUE TITLE
Hardware BP causes a problem in (snapshot_2015-04-17_03-42)

### ISSUE THREAD

**Issue by wk-952** [x64dbg/x64dbg#284] opened 2015-04-18 17:21 UTC
After setting a hardware BP then restarting the process,
or loading any application whose database contains a hardware BP
causes an issue in the debugger.

No crashes occur but the debugger hangs and it can only be closed from the Task Manager.
This is the output from the log tab:

------------------------------------------

Process Started: 00400000 D:\Installed\tst_a\asdzxc.exe
Database file: E:\Programs\Sources\x64_dbg\x32\db\asdzxc.exe.dd32
Loading database...0ms

------------------------------------------

And the disassembly window is completely empty.

**Comment by RaMMicHaeL** [comment] 2015-04-18 17:42
The same happened to me today, but when attaching.
Stack trace:
```
Address           To                From              Comment                                                                                                                                                                                                                    
00000071A096C218  00007FFE0A3F13ED  00007FFE0A4F9D70  return to kernelbase.00007FFE0A3F13ED from kernelbase.__imp_NtWaitForMultipleObjects                                                                                                                                       
00000071A096C298  FFFFFFFFFFFFFFFF  0000000000108982  return to FFFFFFFFFFFFFFFF from 0000000000108982                                                                                                                                                                           
00000071A096C2A0  FFFFFFFFFFFFFFFF  0000000000108982  return to FFFFFFFFFFFFFFFF from 0000000000108982                                                                                                                                                                           
00000071A096C2A8  00007FFE0A3F167F  00007FFE0A4F9CF0  return to kernelbase.00007FFE0A3F167F from kernelbase.__imp_RtlActivateActivationContextUnsafeFast                                                                                                                         
00000071A096C2D8  00007FFE0A40921B  00007FFE0A4FA0B0  return to kernelbase.00007FFE0A40921B from kernelbase.__imp_RtlUnlockHeap                                                                                                                                                  
00000071A096C2E0  FFFFFFFFFFFFFFFE  00000000000F0E93  return to FFFFFFFFFFFFFFFE from 00000000000F0E93                                                                                                                                                                           
00000071A096C308  00007FFE0A40921B  00007FFE0A4FA0B0  return to kernelbase.00007FFE0A40921B from kernelbase.__imp_RtlUnlockHeap                                                                                                                                                  
00000071A096C338  00007FFE0A742712  00007FFE0A76C518  return to imm32.00007FFE0A742712 from imm32.00007FFE0A76C518                                                                                                                                                               
00000071A096C348  00007FFE0CF5C187  00007FFE0CFC2590  return to ntdll.00007FFE0CF5C187 from ntdll.00007FFE0CFC2590                                                                                                                                                               
00000071A096C378  00007FFE0B07C363  00007FFE0B179AB0  return to msctf.00007FFE0B07C363 from msctf.00007FFE0B179AB0                                                                                                                                                               
00000071A096C418  00007FFE0A5C2E1F                    return to user32.00007FFE0A5C2E1F from ???                                                                                                                                                                                 
00000071A096C458  00007FFE0A5C2532  00007FFE0A66D230  return to user32.00007FFE0A5C2532 from user32.00007FFE0A66D230                                                                                                                                                             
00000071A096C4F8  00007FFE0A5C32B4  00007FFE0A66D448  return to user32.00007FFE0A5C32B4 from user32.00007FFE0A66D448                                                                                                                                                             
00000071A096C528  00007FFE0A5C2367  00007FFE0A5C23C0  return to user32.00007FFE0A5C2367 from user32.00007FFE0A5C23C0                                                                                                                                                             
00000071A096C5A8  0000000051A62953  0000000051AB27E0  return to qtcore4.0000000051A62953 from qtcore4.0000000051AB27E0                                                                                                                                                           
00000071A096C628  0000000051A4D607  0000000051A4C7B0  return to qtcore4.0000000051A4D607 from qtcore4.public: void __cdecl QObjectPrivate::addConnection(int,struct QObjectPrivate::Connection * __ptr64) __ptr64                                                                
00000071A096C748  00007FFE0CF707C7  00007FFE0CF70910  return to ntdll.00007FFE0CF707C7 from ntdll.00007FFE0CF70910                                                                                                                                                               
00000071A096C758  0000000051DBAE07  00000000522EC4B0  return to qtgui4.0000000051DBAE07 from qtgui4.00000000522EC4B0                                                                                                                                                             
00000071A096C768  0000000051DBAE07  00000000522EC4B0  return to qtgui4.0000000051DBAE07 from qtgui4.00000000522EC4B0                                                                                                                                                             
00000071A096C7B8  0000000051A40D8D                    return to qtcore4.0000000051A40D8D from ???                                                                                                                                                                                
00000071A096C7D8  0000000052106ED1  00000000523518C0  return to qtgui4.0000000052106ED1 from qtgui4.00000000523518C0                                                                                                                                                             
00000071A096C7E8  0000000052106E7E  0000000052351700  return to qtgui4.0000000052106E7E from qtgui4.0000000052351700                                                                                                                                                             
00000071A096C818  0000000051DB1277                    return to qtgui4.0000000051DB1277 from ???                                                                                                                                                                                 
00000071A096C838  0000000051DB1277                    return to qtgui4.0000000051DB1277 from ???                                                                                                                                                                                 
00000071A096C848  0000000051DB1277                    return to qtgui4.0000000051DB1277 from ???                                                                                                                                                                                 
00000071A096C858  00007FFE0CF6FCD3  00007FFE0CFC2590  return to ntdll.00007FFE0CF6FCD3 from ntdll.00007FFE0CFC2590                                                                                                                                                               
00000071A096C898  00007FFE0CF707C7  00007FFE0CF70910  return to ntdll.00007FFE0CF707C7 from ntdll.00007FFE0CF70910                                                                                                                                                               
00000071A096C8C8  00000000520D3FB3  00000000523518C0  return to qtgui4.00000000520D3FB3 from qtgui4.00000000523518C0                                                                                                                                                             
00000071A096C8F8  0000000052144E58  00000000520D3F70  return to qtgui4.0000000052144E58 from qtgui4.protected: virtual bool __cdecl QFrame::event(class QEvent * __ptr64) __ptr64                                                                                                
00000071A096C948  00007FFE0CF707C7  00007FFE0CF70910  return to ntdll.00007FFE0CF707C7 from ntdll.00007FFE0CF70910                                                                                                                                                               
00000071A096C960  FFFFFFFFFFFFFFFE  0000000000000147  return to FFFFFFFFFFFFFFFE from 0000000000000147                                                                                                                                                                           
00000071A096C978  0000000051DCA9FD  00000000522EC4B0  return to qtgui4.0000000051DCA9FD from qtgui4.00000000522EC4B0                                                                                                                                                             
00000071A096C988  0000000051DCA9FD  00000000522EC4B0  return to qtgui4.0000000051DCA9FD from qtgui4.00000000522EC4B0                                                                                                                                                             
00000071A096C998  0000000052087EF9  0000000052351888  return to qtgui4.0000000052087EF9 from qtgui4.0000000052351888                                                                                                                                                             
00000071A096C9B8  00000000521081B5  0000000051DB07E0  return to qtgui4.00000000521081B5 from qtgui4.protected: virtual bool __cdecl QWidget::event(class QEvent * __ptr64) __ptr64                                                                                               
00000071A096CA18  0000000051D5BCBA  0000000052351878  return to qtgui4.0000000051D5BCBA from qtgui4.0000000052351878                                                                                                                                                             
00000071A096CA28  0000000051A3F883                    return to qtcore4.0000000051A3F883 from ???                                                                                                                                                                                
00000071A096CA58  0000000051D72D16                    return to qtgui4.0000000051D72D16 from ???                                                                                                                                                                                 
00000071A096CA88  0000000051D729B0  0000000051D72C20  return to qtgui4.0000000051D729B0 from qtgui4.public: bool __cdecl QApplicationPrivate::notify_helper(class QObject * __ptr64,class QEvent * __ptr64) __ptr64                                                              
00000071A096CAF8  00007FFE0CF707C7  00007FFE0CF70910  return to ntdll.00007FFE0CF707C7 from ntdll.00007FFE0CF70910                                                                                                                                                               
00000071A096CBC8  00007FFE0CF707C7  00007FFE0CF70910  return to ntdll.00007FFE0CF707C7 from ntdll.00007FFE0CF70910                                                                                                                                                               
00000071A096CC08  00007FFDEFA06A57  00007FFDEFA483E0  return to msvcr120.00007FFDEFA06A57 from msvcr120.00007FFDEFA483E0                                                                                                                                                         
00000071A096CC18  FFFFFFFFFFFFFFFE  0000000000041987  return to FFFFFFFFFFFFFFFE from 0000000000041987                                                                                                                                                                           
00000071A096CC38  0000000051A51AAD  00000000519A6BC0  return to qtcore4.0000000051A51AAD from qtcore4.public: static struct QVectorData * __ptr64 __cdecl QVectorData::allocate(int,int)                                                                                         
00000071A096CC58  0000000051A6E63A  0000000051A6E270  return to qtcore4.0000000051A6E63A from qtcore4.0000000051A6E270                                                                                                                                                           
00000071A096CD18  00007FFDE5C13E48  00007FFDE5CEB568  return to x64gui.00007FFDE5C13E48 from x64gui.00007FFDE5CEB568                                                                                                                                                             
00000071A096CD58  0000000051D65463  0000000052351850  return to qtgui4.0000000051D65463 from qtgui4.0000000052351850                                                                                                                                                             
00000071A096CD68  0000000051A3DA7D  0000000051A97A90  return to qtcore4.0000000051A3DA7D from qtcore4.0000000051A97A90                                                                                                                                                           
00000071A096CDE8  0000000051D60210  0000000051D83BF0  return to qtgui4.0000000051D60210 from qtgui4.public: virtual __cdecl QActionEvent::~QActionEvent(void) __ptr64                                                                                                            
00000071A096CE48  0000000051D6183C  0000000051D60110  return to qtgui4.0000000051D6183C from qtgui4.0000000051D60110                                                                                                                                                             
00000071A096CE78  00007FFDE5C1687A  00007FFDE5C317B0  return to x64gui.00007FFDE5C1687A from x64gui.00007FFDE5C317B0                                                                                                                                                             
00000071A096CEC8  00007FFDE5CBF135  00007FFDE5C16700  return to x64gui.00007FFDE5CBF135 from x64gui.00007FFDE5C16700                                                                                                                                                             
00000071A096CEF8  00007FFDE5CBF135  00007FFDE5C16700  return to x64gui.00007FFDE5CBF135 from x64gui.00007FFDE5C16700                                                                                                                                                             
00000071A096CF28  00007FFDEFA06A57  00007FFDEFA483E0  return to msvcr120.00007FFDEFA06A57 from msvcr120.00007FFDEFA483E0                                                                                                                                                         
00000071A096CF38  000000005195820A  0000000051AB2088  return to qtcore4.000000005195820A from qtcore4.0000000051AB2088                                                                                                                                                           
00000071A096CF58  0000000051995122  000000005194F230  return to qtcore4.0000000051995122 from qtcore4.void * __ptr64 __cdecl qMalloc(unsigned __int64)                                                                                                                           
00000071A096CF68  0000000051A4C4B1                    return to qtcore4.0000000051A4C4B1 from ???                                                                                                                                                                                
00000071A096CF88  0000000051A6E56D  00000000519A2D60  return to qtcore4.0000000051A6E56D from qtcore4.public: void __cdecl QString::truncate(int) __ptr64                                                                                                                        
00000071A096D030  00000071A096D0D8                    return to 00000071A096D0D8 from ???                                                                                                                                                                                        
00000071A096D038  00007FFDE5CC0C2C  00007FFDE5CC93D0  return to x64gui.00007FFDE5CC0C2C from x64gui.00007FFDE5CC93D0                                                                                                                                                             
00000071A096D070  00000071A096D0D8                    return to 00000071A096D0D8 from ???                                                                                                                                                                                        
00000071A096D078  00007FFDE5CBBBC9  00007FFDE5C31750  return to x64gui.00007FFDE5CBBBC9 from x64gui.00007FFDE5C31750                                                                                                                                                             
00000071A096D088  00000071A096D0D8                    return to 00000071A096D0D8 from ???                                                                                                                                                                                        
00000071A096D098  00007FFDE5C30FB3  00007FFDE5CBBBC0  return to x64gui.00007FFDE5C30FB3 from x64gui.00007FFDE5CBBBC0                                                                                                                                                             
00000071A096D0A8  00007FFDE5C30F5C  00007FFDE5CE9A00  return to x64gui.00007FFDE5C30F5C from x64gui.00007FFDE5CE9A00                                                                                                                                                             
00000071A096D0B8  00007FFDE5C3208A  00007FFDE5CC93D0  return to x64gui.00007FFDE5C3208A from x64gui.00007FFDE5CC93D0                                                                                                                                                             
00000071A096D0E8  00007FFDE5C3208A  00007FFDE5CC93D0  return to x64gui.00007FFDE5C3208A from x64gui.00007FFDE5CC93D0                                                                                                                                                             
00000071A096D138  00007FFDE5C3208A  00007FFDE5CC93D0  return to x64gui.00007FFDE5C3208A from x64gui.00007FFDE5CC93D0                                                                                                                                                             
00000071A096D288  00007FFE0CF707C7  00007FFE0CF70910  return to ntdll.00007FFE0CF707C7 from ntdll.00007FFE0CF70910                                                                                                                                                               
00000071A096D398  00007FFE0CF6E83F  00007FFE0CFC2590  return to ntdll.00007FFE0CF6E83F from ntdll.00007FFE0CFC2590                                                                                                                                                               
00000071A096D568  00007FFE0CF707C7  00007FFE0CF70910  return to ntdll.00007FFE0CF707C7 from ntdll.00007FFE0CF70910                                                                                                                                                               
00000071A096D638  00007FFE0CF6E03E  00007FFE0CFC2590  return to ntdll.00007FFE0CF6E03E from ntdll.00007FFE0CFC2590                                                                                                                                                               
00000071A096D678  00007FFE0CFAA6B7  00007FFE0CFD4E00  return to ntdll.00007FFE0CFAA6B7 from ntdll.RtlMoveMemory                                                                                                                                                                  
00000071A096D748  00007FFE0CFAA2BB  00007FFE0CF75130  return to ntdll.00007FFE0CFAA2BB from ntdll.RtlFreeHeap                                                                                                                                                                    
00000071A096D7A8  00007FFE0A40C4F2  00007FFE0A4FA108  return to kernelbase.00007FFE0A40C4F2 from kernelbase.__imp_RtlSetCurrentDirectory_U                                                                                                                                       
00000071A096D7E8  00007FFDFF0E7C5A  00007FFDFF0FE720  return to x64dbg.00007FFDFF0E7C5A from x64dbg.00007FFDFF0FE720                                                                                                                                                             
00000071A096D878  0000000051A420D6  0000000051A97A90  return to qtcore4.0000000051A420D6 from qtcore4.0000000051A97A90                                                                                                                                                           
00000071A096D898  00007FFE0CF6E03E  00007FFE0CFC2590  return to ntdll.00007FFE0CF6E03E from ntdll.00007FFE0CFC2590                                                                                                                                                               
00000071A096D8F8  00007FFE0CF6E03E  00007FFE0CFC2590  return to ntdll.00007FFE0CF6E03E from ntdll.00007FFE0CFC2590                                                                                                                                                               
00000071A096D958  00007FFE0CF7ADB9  00007FFE0CF7B0E0  return to ntdll.00007FFE0CF7ADB9 from ntdll.RtlReleaseSRWLockExclusive                                                                                                                                                     
00000071A096D988  00007FFE0CF7AC41  00007FFE0CF7ADA0  return to ntdll.00007FFE0CF7AC41 from ntdll.00007FFE0CF7ADA0                                                                                                                                                               
00000071A096DA08  00007FFE0CFB7C82  00007FFE0CFC2590  return to ntdll.00007FFE0CFB7C82 from ntdll.00007FFE0CFC2590                                                                                                                                                               
00000071A096DC68  00007FFE0CFB7A93  00007FFE0CFC2590  return to ntdll.00007FFE0CFB7A93 from ntdll.00007FFE0CFC2590                                                                                                                                                               
00000071A096DF18  00007FFE0CF6D4CB  00007FFE0CFD4E00  return to ntdll.00007FFE0CF6D4CB from ntdll.RtlMoveMemory                                                                                                                                                                  
00000071A096DF68  00007FFE0CF702D2  00007FFE0CF703C0  return to ntdll.00007FFE0CF702D2 from ntdll.RtlMultiByteToUnicodeN                                                                                                                                                         
00000071A096DFD8  00007FFE0CF6D04E  00007FFE0CFC2590  return to ntdll.00007FFE0CF6D04E from ntdll.00007FFE0CFC2590                                                                                                                                                               
00000071A096E098  00007FFE0CF7CB96  00007FFE0CF7CD70  return to ntdll.00007FFE0CF7CB96 from ntdll.RtlImageNtHeaderEx                                                                                                                                                             
00000071A096E118  00007FFE0CF7C0E1  00007FFE0CF7C2D0  return to ntdll.00007FFE0CF7C0E1 from ntdll.00007FFE0CF7C2D0                                                                                                                                                               
00000071A096E178  00007FFE0CF7B9B8  00007FFE0CF7BA90  return to ntdll.00007FFE0CF7B9B8 from ntdll.RtlReleaseSRWLockShared                                                                                                                                                        
00000071A096E1A8  00007FFE0CF7B96B  00007FFE0CF7B99C  return to ntdll.00007FFE0CF7B96B from ntdll.00007FFE0CF7B99C                                                                                                                                                               
00000071A096E1E8  00007FFE0CF7BF70  00007FFE0CFC2590  return to ntdll.00007FFE0CF7BF70 from ntdll.00007FFE0CFC2590                                                                                                                                                               
00000071A096E2D8  00007FFE0CF58CF3  00007FFE0CF7BF88  return to ntdll.00007FFE0CF58CF3 from ntdll.00007FFE0CF7BF88                                                                                                                                                               
00000071A096E338  00007FFE0D0015B7  00007FFE0CF7B0E0  return to ntdll.00007FFE0D0015B7 from ntdll.RtlReleaseSRWLockExclusive                                                                                                                                                     
00000071A096E398  00007FFE0CFB6469  00007FFE0CF7DA78  return to ntdll.00007FFE0CFB6469 from ntdll.00007FFE0CF7DA78                                                                                                                                                               
00000071A096E498  00007FFE0CF70C65  00007FFE0CFD5140  return to ntdll.00007FFE0CF70C65 from ntdll.memset                                                                                                                                                                         
00000071A096E568  00007FFE0CF707C7  00007FFE0CF70910  return to ntdll.00007FFE0CF707C7 from ntdll.00007FFE0CF70910                                                                                                                                                               
00000071A096E628  00007FFE0CF67B06  00007FFE0CFD4E00  return to ntdll.00007FFE0CF67B06 from ntdll.RtlMoveMemory                                                                                                                                                                  
00000071A096E678  00007FFE0A3F19A5  00007FFE0A4F98E8  return to kernelbase.00007FFE0A3F19A5 from kernelbase.__imp_RtlAllocateHeap                                                                                                                                                
00000071A096E6A8  00007FFE0A3F2593  00007FFE0A4F9128  return to kernelbase.00007FFE0A3F2593 from kernelbase.__imp_RtlSetLastWin32Error                                                                                                                                           
00000071A096E6E8  00007FFE088BE8F8  00007FFE08891560  return to shcore.00007FFE088BE8F8 from shcore.00007FFE08891560                                                                                                                                                             
00000071A096E808  00007FFE0CF7AB7F  00007FFE0CF7B0E0  return to ntdll.00007FFE0CF7AB7F from ntdll.RtlReleaseSRWLockExclusive                                                                                                                                                     
00000071A096E858  00007FFE0CF7DA54  00007FFE0CF7DA78  return to ntdll.00007FFE0CF7DA54 from ntdll.00007FFE0CF7DA78                                                                                                                                                               
00000071A096E8B8  00007FFE0B6618EB  00007FFE0B6618F0  return to shell32.00007FFE0B6618EB from shell32.00007FFE0B6618F0                                                                                                                                                           
00000071A096E928  00007FFE0A3F1902  00007FFE0A4FA200  return to kernelbase.00007FFE0A3F1902 from kernelbase.__imp_RtlFreeHeap                                                                                                                                                    
00000071A096E968  00007FFDFF0FA54E  00007FFDFF0FE720  return to x64dbg.00007FFDFF0FA54E from x64dbg.00007FFDFF0FE720                                                                                                                                                             
00000071A096E9D8  0000000051A3C5FB  0000000051A3B770  return to qtcore4.0000000051A3C5FB from qtcore4.0000000051A3B770                                                                                                                                                           
00000071A096E9E8  0000000051D6ACA2  00000000522EC580  return to qtgui4.0000000051D6ACA2 from qtgui4.00000000522EC580                                                                                                                                                             
00000071A096F0C8  FFFFFFFFFFFFFFFE  00000000005818DC  return to FFFFFFFFFFFFFFFE from 00000000005818DC                                                                                                                                                                           
00000071A096F7A8  00007FFE0CF707C7  00007FFE0CF70910  return to ntdll.00007FFE0CF707C7 from ntdll.00007FFE0CF70910                                                                                                                                                               
00000071A096F7E8  00007FFE0CF707C7  00007FFE0CF70910  return to ntdll.00007FFE0CF707C7 from ntdll.00007FFE0CF70910                                                                                                                                                               
00000071A096F8B8  00007FFDEFA06A57  00007FFDEFA483E0  return to msvcr120.00007FFDEFA06A57 from msvcr120.00007FFDEFA483E0                                                                                                                                                         
00000071A096F8E8  0000000051A6242C  0000000051A97B50  return to qtcore4.0000000051A6242C from qtcore4.0000000051A97B50                                                                                                                                                           
00000071A096F918  0000000051DD0BA5  0000000052352648  return to qtgui4.0000000051DD0BA5 from qtgui4.0000000052352648                                                                                                                                                             
00000071A096F948  0000000051A3A9FC                    return to qtcore4.0000000051A3A9FC from ???                                                                                                                                                                                
00000071A096F9B8  0000000051A3CFB0  0000000051A3A7D0  return to qtcore4.0000000051A3CFB0 from qtcore4.public: int __cdecl QEventLoop::exec(class QFlags<enum QEventLoop::ProcessEventsFlag>) __ptr64                                                                             
00000071A096F9F8  00007FFDFF0FA484  00007FFDFF0FE850  return to x64dbg.00007FFDFF0FA484 from x64dbg.00007FFDFF0FE850                                                                                                                                                             
00000071A096FA08  00007FFDE5C14276  00007FFDE5CEB570  return to x64gui.00007FFDE5C14276 from x64gui.00007FFDE5CEB570                                                                                                                                                             
00000071A096FA38  00007FFE0CF9FE72  00007FFE0CF7B0E0  return to ntdll.00007FFE0CF9FE72 from ntdll.RtlReleaseSRWLockExclusive                                                                                                                                                     
00000071A096FA48  00007FFE018A6591  00007FFE018AA030  return to x64bridge.00007FFE018A6591 from x64bridge.00007FFE018AA030                                                                                                                                                       
00000071A096FBC8  00007FFE018A6A90                    return to x64bridge.00007FFE018A6A90 from ???                                                                                                                                                                              
00000071A096FBF8  00007FF7C4F51037  00007FF7C4F52110  return to x64dbg.00007FF7C4F51037 from x64dbg.00007FF7C4F52110                                                                                                                                                             
00000071A096FC28  00007FF7C4F512DD  00007FF7C4F51000  return to x64dbg.00007FF7C4F512DD from x64dbg.00007FF7C4F51000                                                                                                                                                             
00000071A096FC68  00007FFE0ABB13D2                    return to kernel32.00007FFE0ABB13D2 from ???                                                                                                                                                                               
00000071A096FC98  00007FFE0CF55444                    return to ntdll.00007FFE0CF55444 from ???                                                                                                                                                                                  
```

**Comment by wk-952** [comment] 2015-04-24 08:49
any updates concerning this issue?

**Comment by mrexodia** [comment] 2015-04-24 08:53
I couldn't reproduce it yet...

**Comment by wk-952** [comment] 2015-04-24 11:47
This file contains a simple crackMe from Lena151's tutorials
along with the database file from x64dbg.

Please try to debug this application using the provided database file
with (snapshot_2015-04-17_03-42) from SourceForge and see if it will work for you.

**Comment by mrfearless** [comment] 2015-04-24 18:07
Tried the above file with and without the included database. If "titantype": "0xB47" and "type": 1 then it does as described by wk-952. If you edit the database file to "titantype": "0x0" and "type": 0 then program works as expected after restart (and after killing x32dbg from task manager). I then reset everything, confirmed the settings in the .db32 were no breakpoints, and set hardware breakpoint on the same address, after restart, hangs/does nothing, have to kill from task manager to close x32dbg.

**Comment by Nukem9** [comment] 2015-04-24 19:13
Seems to work fine now with the latest commit. Closing when someone else can confirm this.

**Comment by wk-952** [comment] 2015-04-24 20:08
I've downloaded and re-compiled the project and yes the issue is gone now,
thank you very much.

**Closed** 2015-04-24 20:17 UTC

**Comment by mrexodia** [comment] 2015-04-24 20:43
:+1:
