### ISSUE TITLE
Feature Request: Run until condition is satisfied

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#207] opened 2015-04-12 18:46 UTC
In OllyDbg there is a dialog to setup certain conditions when the debuger must pause its execution. For example, the execution will stop until the EIP register is between a specified address range, or if the command X if found, and so on. That would be nice to having this feature present in x64dbg.

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/207
- Originally reported by: Ferdnand F.
- Originally created at: 2014-09-24T22:08:52.811

**Comment by mrexodia** [comment] 2015-07-13 04:17
duplicate of #85

**Closed by mrexodia** 2015-07-13 04:17 UTC
