### ISSUE TITLE
gui issues

### ISSUE THREAD

**Issue by freesoft0000** [x64dbg/x64dbg#1664] opened 2017-07-28 03:42 UTC
The system is windows7 32 bit 
DPI is 125% 
X64dbg version 2017-7-23 

- [ ] I wonder if x64dbg's support for high DPI is perfect?
- [ ] Chinese language interface, some of the buttons of text display incomplete
- [ ] The default font for x64dbg is also small and can be changed larger. Large monitors are now widely used, so small fonts can blind people. 😄 
- [ ] The x64dbg menu sometimes hits very quickly and doesn't work. Need to click again.
For example, click file - open, or the shortcut menu in the right

**Comment by mrexodia** [comment] 2017-07-28 13:07
Could you give a screenshot for each of these problems and please provide ways to reproduce the last issue. There is no high DPI support in x64dbg because I don't have a high DPI monitor.

**Comment by freesoft0000** [comment] 2017-07-28 15:51
![image 1](https://user-images.githubusercontent.com/30435921/28725266-88a90586-73ef-11e7-91de-83d8aaad2ea0.png)
![image 2](https://user-images.githubusercontent.com/30435921/28725262-88304c90-73ef-11e7-9a65-7555a260c56e.png)
![image 3](https://user-images.githubusercontent.com/30435921/28725264-88386b00-73ef-11e7-8488-2c6b711e0190.png)
![image 4](https://user-images.githubusercontent.com/30435921/28725263-8835acbc-73ef-11e7-923d-a275f1b4ff49.png)
![image 5](https://user-images.githubusercontent.com/30435921/28725268-890946ee-73ef-11e7-84c7-20f2cf8afa59.png)

**Comment by freesoft0000** [comment] 2017-07-28 16:45
> The x64dbg menu sometimes hits very quickly and doesn't work. Need to click again.
>  For example, click file - open, or the shortcut menu in the right
Problem reproduction video, in about 30 seconds, you can see I clicked, but it didn't work. 
Sorry, the video file is relatively large, so it can't be uploaded here. Stored in the cloud tray. Enclosed please find。 
https://mega.nz/#!FfQmhLqJ!6rfdHY0b0S3aeK8jvRq96UhBwzMhgZD_FV9Fzercap8

**Comment by peterius** [comment] 2017-07-30 23:15
That's weird, I wonder if it's all a DPI issue.  I thought Qt strings automatically resized their buttons?  Maybe There's some particular Qt DPI awareness stuff?  Does button text fit the button if DPI is turned off?

**Comment by freesoft0000** [comment] 2017-07-31 01:19
When DPI is 100%, the program interface text is displayed normally

**Comment by peterius** [comment] 2017-08-03 01:01
https://stackoverflow.com/questions/20464814/changing-dpi-scaling-size-of-display-make-qt-applications-font-size-get-rendere
QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling)   ?

Seems pretty easy?  To be honest, I still haven't had time to get x64dbg to compile.  It doesn't like my Qt setup so everything links up and then when I run it it complains about the libraries and the bridge and missing symbols.

**Comment by mrexodia** [comment] 2017-08-03 15:35
I added this to the GUI main function (but I cannot test it because I don't have a high DPI display)

**Comment by peterius** [comment] 2017-08-09 23:46
I don't know.  I got it compiling.  When I set my screen to 150% DPI scaling, it looked fine.  But strangely at 125%, the "restore selected" button on the patches dialog was again squished.  It may have helped, I'm not sure.

**Comment by freesoft0000** [comment] 2017-08-11 04:29
x64dbg version 2017-7-23
DPI 150% is also normal. DPI 125% does not show full

**Comment by freesoft0000** [comment] 2017-08-15 02:07
The new version does not fix the problem.

**Comment by blaquee** [comment] 2017-08-15 02:12
Why did you close the issue if the problem was not resolved?

**Comment by freesoft0000** [comment] 2017-08-15 02:13
I do not understand English, want to reply, but wrong operation

**Comment by freesoft0000** [comment] 2017-08-15 08:00
thanks

**Comment by freesoft0000** [comment] 2017-08-16 07:42
http://doc.qt.io/qt-5/highdpi.html
http://blog.qt.io/blog/2016/01/26/high-dpi-support-in-qt-5-6/

**Comment by mrexodia** [comment] 2017-08-16 08:01
Those articles are useless to be because I don't have a high dpi monitor... What code should I add?

**Comment by freesoft0000** [comment] 2017-08-16 11:58
I don't know exactly.

**Comment by freesoft0000** [comment] 2017-08-16 12:04
> The x64dbg menu sometimes hits very quickly and doesn't work. Need to click again.
>  For example, click file - open, or the shortcut menu in the right
Can this problem be repaired?
The latest version problem is still

**Comment by mrexodia** [comment] 2017-08-16 18:11
Feel free to repair it yourself. Like I said I cannot test this bug.

**Comment by tambry** [comment] 2017-08-26 09:53
@mrexodia You don't need a HiDPI monitor to enable DPI scaling. In Windows 10 you can simply go into Settings -> System -> Display, ![select a DPI scaling factor](https://i.imgur.com/uh5wdTt.png) and hit apply. On previous Windows versions the process is much more annoying (may require restarts) and doesn't support per-monitor DPI scaling.

**Comment by eladkarako** [comment] 2022-05-29 23:15
you can try the GDI-scaling variation published in here: 
https://github.com/x64dbg/x64dbg/issues/2877#issuecomment-1140466026 (under "notes").

**Closed** 2024-09-02 12:01 UTC
Labels: enhancement, gui
