### ISSUE TITLE
copy memory or heap stack like ollydbg?

### ISSUE THREAD

**Issue by xinxirong** [x64dbg/x64dbg#690] opened 2016-06-01 07:03 UTC
it may be very simple to do:copy memory or heap stack like ollydbg?

**Comment by mrexodia** [comment] 2016-06-01 07:04
there is a command called `memcpy` but I don't quite understand what you want to do.

**Comment by xinxirong** [comment] 2016-06-02 00:35
like this,you can copy view in Memory,and the heap/stack view
![odcopy](https://cloud.githubusercontent.com/assets/10396893/15730169/e09a1b62-289c-11e6-9787-6a7764346d0f.png)

**Comment by torusrxxx** [comment] 2016-06-02 01:04
Copy the text representation of the stack view.

**Comment by mrexodia** [comment] 2016-06-02 06:44
duplicate of #232

**Closed by mrexodia** 2016-06-02 06:44 UTC
Labels: feature, not reproduced

**Comment by xinxirong** [comment] 2016-06-03 02:56
#232 for many years still here,no one solute it ?

**Comment by mrexodia** [comment] 2016-06-03 04:03
Yes if you want something to happen quick the only way is to do it yourself.

**Comment by torusrxxx** [comment] 2016-06-03 05:15
I will add it soon for customer satisfactory.
There have been **few contributers** contributing. I just worked **full time** for a few days and I becomes one of the top contributers. I need the best debugger to work with. I used to rely on precompiled software and writing private plugins, but I now contribute to an open-source project and do not have to complain. So if you want new feature, do it yourself and contribute back is probably the most efficient way. And instead of writing plugins I add these features directly into the core. I'll be enjoying my custom-made debugger next month with every feature I want.
