### ISSUE TITLE
x64dbg not showing unnamed exports

### ISSUE THREAD

**Issue by dim0x69** [x64dbg/x64dbg#1655] opened 2017-07-18 10:50 UTC
Hi,

thank you for this great project. I am pretty amazed what a great tool you are building. I am just starting to getting in touch with it, so if this issue already was solved somewhere, please excuse me :) 

I am currently debugging a dll which has no Export Name Table, so a function in this dll is called through its ordinal. 

- Debugger version: 03.07.2017, 06:23:54
- OS: Win7 SP1, 64 Bit
- 32 bit DLL, unnamed exports are missing

![18-07-2017 11-31-25](https://user-images.githubusercontent.com/1571696/28313626-defd7024-6bb7-11e7-8ccf-ee77ae38387e.png)

- The DLL is NoPetya, so I think I should not upload it here? I can give you the sample...

**Comment by mrexodia** [comment] 2017-07-25 11:45
This is a duplicate of #580

**Closed by mrexodia** 2017-07-25 11:45 UTC
Labels: bug
