### ISSUE TITLE
x32dbg guard pages

### ISSUE THREAD

**Issue by bobcfgxp** [x64dbg/x64dbg#877] opened 2016-07-22 14:42 UTC
Debugging a 32 bit process on Windows 10 x64. Start up notepad, pause it, perform a "find pattern" from the memory map, resume and the debugger will report that guard pages have been hit, EXCEPTION_GUARD_PAGE. This in turn causes the app to crash.

INT3 breakpoint "entry breakpoint" at <notepad.EntryPoint> (00B859F0)!
DLL Loaded: 6E9D0000 C:\Windows\SysWOW64\uxtheme.dll
DLL Loaded: 6E230000 C:\Windows\SysWOW64\dwmapi.dll
62 occurrences found in 1282ms
First chance exception on 63C618F0 (80000001, EXCEPTION_GUARD_PAGE)!
Last chance exception on 63C618F0 (80000001, EXCEPTION_GUARD_PAGE)!
First chance exception on 0091FD1C (C0000005, EXCEPTION_ACCESS_VIOLATION)!
Last chance exception on 0091FD1C (C0000005, EXCEPTION_ACCESS_VIOLATION)!

**Comment by dooley71** [comment] 2016-07-23 16:19
I coincidently posted the same issue which was closed down because it was a duplicate of your post. 

I will follow to see if we can find an answer to this.

Out of curiosity, has this always happened to you when using x32dbg or did it just start recently?

I don't remember it happening in the past.

**Comment by mrexodia** [comment] 2016-07-23 17:44
I didn't look for patterns in the memory map recently. My guess is that something fishy is going on in the memory read procedures.

**Comment by bobcfgxp** [comment] 2016-07-28 06:58
I have only started using it recently and x64dbg works fine, but it strikes me as strange that noone has noticed it before. I was working from an oldish version (5 months) but the latest was still affected. Awesome tool, but makes it impossible to use for my current task.

**Comment by mrexodia** [comment] 2016-07-28 07:38
Are you guys ok windows 10 perhaps? I tried reproducing the issue but I didn't have any problems on Windows 8.1

**Comment by mrexodia** [comment] 2016-07-28 07:39
Nevermind op is indeed on Windows 10.

**Comment by wk-952** [comment] 2016-07-29 02:13
I can confirm this on Win10 x64, searching for references in memory map while debugging `notepad.exe` (doesn't matter if paused or not) will throw `EXCEPTION_GUARD_PAGE` and sometimes along with it `STATUS_USER_CALLBACK`.
This seems to be only happening with `notepad.exe`, never had this problem with any other application.

log:
```
1 occurrences found in 640ms
First chance exception on 262976B6 (80000001, EXCEPTION_GUARD_PAGE)!
Last chance exception on 262976B6 (C000041D, STATUS_USER_CALLBACK)!
```
Will the minidump files be of any help for this ?

**Comment by mrexodia** [comment] 2016-07-29 10:10
I don't think there will be any minidumps since x64dbg itself doesn't
crash. You could try running the 'exinfo' command on the exceptions, maybe
it gives some more information...

**Comment by wk-952** [comment] 2016-07-29 12:06
This is the information given by `exinfo`:
```
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: 80000001 (EXCEPTION_GUARD_PAGE)
          ExceptionFlags: 00000000
        ExceptionAddress: 262976B6
        NumberParameters: 2
ExceptionInformation[00]: 00000000
ExceptionInformation[01]: 04EDFD22

```
Tried a couple of other applications now and it happened with them too, so not only notepad.
I actually meant manually generating those minidumps (Help --> Generate crash dump), here they are anyway just in case they're of any help.
http://rgho.st/private/6l66z9Zc4/f6b6d7d8bc367217e1006c23e382f59f

**Comment by mrexodia** [comment] 2016-07-29 12:42
What kind of memory is at the addresses mentioned in the exinfo command? I
suspect that they are stacks or something to do with memory protection.

**Comment by wk-952** [comment] 2016-07-29 12:53
I tried following both, `ExceptionAddress` wasn't anything valid, but `ExceptionInformation[01]` was pointing to a memory map that had the following info (the address is different here because that's another test):
```
Address=04E05000
Size=0000B000
Allocation Type=PRV
Current Protection=-RW-G
Allocation Protection=-RW--

```

**Comment by mrexodia** [comment] 2016-07-29 12:55
Did it say 'Thread Xxx stack' in the 'info' section? I think I know what's
going on but I'm not 100% yet.

**Comment by wk-952** [comment] 2016-07-29 12:57
This is pic from the memory map tab (i don't see the word stack):
![untitled](https://cloud.githubusercontent.com/assets/11916365/17248726/9dae521e-559c-11e6-925c-ab0cf8c42f2e.png)

**Comment by wk-952** [comment] 2016-07-30 03:37
@bobcfgxp and @dooley71 could you guys please verify whether you were debugging
`C:\Windows\SysWOW64\notepad.exe` (32-bit version of notepad)
or
`C:\Windows\System32\notepad.exe`  (64-bit version of notepad)
because this seems to be happening for me with the 32-bit version only

**Comment by mrexodia** [comment] 2016-07-30 10:16
It's because of the launcher that is used to start the correct x64dbg
version. That one is 32 bit...

**Comment by mrexodia** [comment] 2016-07-30 10:17
Ehm nevermind wrong issue...

**Comment by dooley71** [comment] 2016-07-30 13:15
I can't reproduce it with either notepad.exe formats. It happens to me with both x32 and x64 with the vast majority of others exe's though.

Not sure if it makes a difference but I wanted to let you guys know that it does not happen to me when searching the local dump, only when searching the memory page.

**Comment by mrexodia** [comment] 2016-07-30 13:36
Same for you @dooley71 could you try with GleeBug?

**Comment by dooley71** [comment] 2016-07-30 15:57
Will do. May be a little while.

**Comment by wk-952** [comment] 2017-08-25 11:15
By the way, this has been fixed almost 7 months ago, if OP wants to confirm.

**Comment by mrexodia** [comment] 2017-09-11 16:03
Assumed fixed.

**Closed** 2017-09-11 16:03 UTC
Labels: bug, not reproduced
