### ISSUE TITLE
Enter expression to follow broken after one navigate operation

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#318] opened 2015-06-14 15:40 UTC
After one navigate operation Ctrl-G show navigate window and there are
http://gyazo.com/5e8003100d8751c20a682cffea1c4d3d
Prev. value looks like frozen or remembered by dialog and nothing changed when typing in edit field and OK button disabled.
upd: frozen even on Ctrl-F2. Latest build from Jun 8 2015

**Comment by mrexodia** [comment] 2015-06-14 17:19
considered a duplicate of #317

**Closed by mrexodia** 2015-06-14 17:19 UTC
