### ISSUE TITLE
tracing

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/x64dbg#222] opened 2015-04-12 19:01 UTC
automatic single stepping and collecting data about the executed instructions and their context.

----------------------------------------
- Bitbucket: https://bitbucket.org/mrexodia/x64_dbg/issue/222
- Originally reported by: [mrexodia](http://bitbucket.org/mrexodia)
- Originally created at: 2014-12-08T23:53:33.176

**Comment by mrexodia** [comment] 2015-07-13 04:18
duplicate of #75

**Closed by mrexodia** 2015-07-13 04:18 UTC
