### ISSUE TITLE
Debugger don't save command line passed in previous debug session

### ISSUE THREAD

**Issue by lupier** [x64dbg/x64dbg#295] opened 2015-05-07 10:03 UTC
When I'm add some command line params to stopped exe at first bp and start debug process all work correctly as expected. After pressing ctrl-f2 debug restarted without previous params.
I want same functionality like in ollydbg when you can press ctrl-f2 and debugger restarted with same param passed in prev. session. and want additional functionality in recent files (also same like in ollydbg) when select old file and params visible also. Hope you can add this feature.

**Comment by mrexodia** [comment] 2015-05-07 10:26
Yea, it might be possible to do this. I'll create a new 'restart' command
that will preserve the command line.

**Comment by mrfearless** [comment] 2015-05-07 20:53
Ive a plugin that remembers command line and auto applies it - even if you restart. Might be helpful to you until mrexodia is able to build in that feature: AutoCmdLine.dp32: https://bitbucket.org/mrfearless/x64dbg-plugin-sdk-for-masm/downloads/AutoCmdLine.dp32 and AutoCmdLine.dp64: https://bitbucket.org/mrfearless/x64dbg-plugin-sdk-for-jwasm64/downloads/AutoCmdLine.dp64

**Comment by lupier** [comment] 2015-05-14 10:35
Many thanks everyone!

**Comment by mrexodia** [comment] 2015-05-14 11:05
It wasn't solved yet :)

**Comment by mrexodia** [comment] 2015-07-13 04:12
duplicate of #254

**Closed by mrexodia** 2015-07-13 04:12 UTC
