### ISSUE TITLE
x64dbg debug chrome,very slowly

### ISSUE THREAD

**Issue by mefcdj** [x64dbg/x64dbg#1533] opened 2017-04-11 15:35 UTC
我用x64dbg调试 chrome的时候，然后从https://chromium-browser-symsrv.commondatastorage.googleapis.com下载了chrome.dll的符号，结果这个pdb文件有 800多MB，结果根本无法调试，因为太卡了，每step一次都要卡很久，不知道能看懂中文吗？？

我的电脑配置cpu I7
内存 16G RAM

**Comment by mefcdj** [comment] 2017-04-11 15:36
我的电脑

**Comment by mrexodia** [comment] 2017-04-11 15:38
The problem lies with dbghelp.dll from Microsoft. I think you will experience the same with windbg. You can try to delete the PDB and everything should be faster or maybe try to strip down the PDB to a smaller size...

**Comment by mrexodia** [comment] 2017-04-12 03:30
considered a duplicate of #747

**Closed by mrexodia** 2017-04-12 03:30 UTC
