### ISSUE TITLE
一些bug和想法

### ISSUE THREAD

**Issue by zbx91** [x64dbg/x64dbg#986] opened 2016-08-16 13:09 UTC
1.无法搜索switch分支.
2.命令栏中无法使用dd db da df dc du等命令，例如：dd [[eax]] 
3.ollydbg中的创建内存功能无，内存被修改后颜色变化
4.x64dbg在搜索文本过程中，如果双击文本，会崩溃.

**Comment by torusrxxx** [comment] 2016-08-16 13:34
He says:

    1. No switch statement support.
    2. Data instructions cannot be specified in the command box.
    3. Data highlighting (related to #813)
    4. Crash while searching for strings (related to #862)

**Comment by mrexodia** [comment] 2016-08-16 13:38
Alright, thanks! There are indeed no commands for data instructions yet
shouldn't be too difficult to add though.

**Comment by mrexodia** [comment] 2016-09-07 11:17
closed as duplicate of #1055 #175 #862 #1054

**Closed by mrexodia** 2016-09-07 11:17 UTC
Labels: bug, not reproduced
